package com.atpuser.Database.Stubs;

public class MunicipalData {
    public static String[] province_municipals = {
            "BUKIDNON|BAUNGON",
            "BUKIDNON|CABANGLASAN",
            "BUKIDNON|CITY OF MALAYBALAY",
            "BUKIDNON|DAMULOG",
            "BUKIDNON|DANGCAGAN",
            "BUKIDNON|DON CARLOS",
            "BUKIDNON|IMPASUG-ONG",
            "BUKIDNON|KADINGILAN",
            "BUKIDNON|KALILANGAN",
            "BUKIDNON|KIBAWE",
            "BUKIDNON|KITAOTAO",
            "BUKIDNON|LANTAPAN",
            "BUKIDNON|LIBONA",
            "BUKIDNON|MALITBOG",
            "BUKIDNON|MANOLO FORTICH",
            "BUKIDNON|MARAMAG",
            "BUKIDNON|PANGANTUCAN",
            "BUKIDNON|QUEZON",
            "BUKIDNON|SAN FERNANDO",
            "BUKIDNON|SUMILAO",
            "BUKIDNON|TALAKAG",
            "BUKIDNON|VALENCIA CITY",
            "CAMIGUIN|CATARMAN",
            "CAMIGUIN|GUINSILIBAN",
            "CAMIGUIN|MAHINOG",
            "CAMIGUIN|MAMBAJAO",
            "CAMIGUIN|SAGAY",
            "LANAO DEL NORTE|BACOLOD",
            "LANAO DEL NORTE|BALOI",
            "LANAO DEL NORTE|BAROY",
            "LANAO DEL NORTE|ILIGAN CITY",
            "LANAO DEL NORTE|KAPATAGAN",
            "LANAO DEL NORTE|KAUSWAGAN",
            "LANAO DEL NORTE|KOLAMBUGAN",
            "LANAO DEL NORTE|LALA",
            "LANAO DEL NORTE|LINAMON",
            "LANAO DEL NORTE|MAGSAYSAY",
            "LANAO DEL NORTE|MAIGO",
            "LANAO DEL NORTE|MATUNGAO",
            "LANAO DEL NORTE|MUNAI",
            "LANAO DEL NORTE|NUNUNGAN",
            "LANAO DEL NORTE|PANTAO RAGAT",
            "LANAO DEL NORTE|PANTAR",
            "LANAO DEL NORTE|POONA PIAGAPO",
            "LANAO DEL NORTE|SALVADOR",
            "LANAO DEL NORTE|SAPAD",
            "LANAO DEL NORTE|SULTAN NAGA DIMAPORO (KAROMATAN)",
            "LANAO DEL NORTE|TAGOLOAN",
            "LANAO DEL NORTE|TANGCAL",
            "LANAO DEL NORTE|TUBOD",
            "MISAMIS OCCIDENTAL|ALORAN",
            "MISAMIS OCCIDENTAL|BALIANGAO",
            "MISAMIS OCCIDENTAL|BONIFACIO",
            "MISAMIS OCCIDENTAL|CALAMBA",
            "MISAMIS OCCIDENTAL|CLARIN",
            "MISAMIS OCCIDENTAL|CONCEPCION",
            "MISAMIS OCCIDENTAL|DON VICTORIANO CHIONGBIAN (DON MARIANO MARCOS)",
            "MISAMIS OCCIDENTAL|JIMENEZ",
            "MISAMIS OCCIDENTAL|LOPEZ JAENA",
            "MISAMIS OCCIDENTAL|OROQUIETA CITY",
            "MISAMIS OCCIDENTAL|OZAMIS CITY",
            "MISAMIS OCCIDENTAL|PANAON",
            "MISAMIS OCCIDENTAL|PLARIDEL",
            "MISAMIS OCCIDENTAL|SAPANG DALAGA",
            "MISAMIS OCCIDENTAL|SINACABAN",
            "MISAMIS OCCIDENTAL|TANGUB CITY",
            "MISAMIS OCCIDENTAL|TUDELA",
            "MISAMIS ORIENTAL|ALUBIJID",
            "MISAMIS ORIENTAL|BALINGASAG",
            "MISAMIS ORIENTAL|BALINGOAN",
            "MISAMIS ORIENTAL|BINUANGAN",
            "MISAMIS ORIENTAL|CAGAYAN DE ORO CITY",
            "MISAMIS ORIENTAL|CLAVERIA",
            "MISAMIS ORIENTAL|EL SALVADOR CITY",
            "MISAMIS ORIENTAL|GINGOOG CITY",
            "MISAMIS ORIENTAL|GITAGUM",
            "MISAMIS ORIENTAL|INITAO",
            "MISAMIS ORIENTAL|JASAAN",
            "MISAMIS ORIENTAL|KINOGUITAN",
            "MISAMIS ORIENTAL|LAGONGLONG",
            "MISAMIS ORIENTAL|LAGUINDINGAN",
            "MISAMIS ORIENTAL|LIBERTAD",
            "MISAMIS ORIENTAL|LUGAIT",
            "MISAMIS ORIENTAL|MAGSAYSAY (LINUGOS)",
            "MISAMIS ORIENTAL|MANTICAO",
            "MISAMIS ORIENTAL|MEDINA",
            "MISAMIS ORIENTAL|NAAWAN",
            "MISAMIS ORIENTAL|OPOL",
            "MISAMIS ORIENTAL|SALAY",
            "MISAMIS ORIENTAL|SUGBONGCOGON",
            "MISAMIS ORIENTAL|TAGOLOAN",
            "MISAMIS ORIENTAL|TALISAYAN",
            "MISAMIS ORIENTAL|VILLANUEVA",
            "COMPOSTELA VALLEY|COMPOSTELA",
            "COMPOSTELA VALLEY|LAAK (SAN VICENTE)",
            "COMPOSTELA VALLEY|MABINI (DOÑA ALICIA)",
            "COMPOSTELA VALLEY|MACO",
            "COMPOSTELA VALLEY|MARAGUSAN (SAN MARIANO)",
            "COMPOSTELA VALLEY|MAWAB",
            "COMPOSTELA VALLEY|MONKAYO",
            "COMPOSTELA VALLEY|MONTEVISTA",
            "COMPOSTELA VALLEY|NABUNTURAN",
            "COMPOSTELA VALLEY|NEW BATAAN",
            "COMPOSTELA VALLEY|PANTUKAN",
            "DAVAO (DAVAO DEL NORTE)|ASUNCION (SAUG)",
            "DAVAO (DAVAO DEL NORTE)|BRAULIO E. DUJALI",
            "DAVAO (DAVAO DEL NORTE)|CARMEN",
            "DAVAO (DAVAO DEL NORTE)|CITY OF TAGUM",
            "DAVAO (DAVAO DEL NORTE)|ISLAND GARDEN CITY OF SAMAL",
            "DAVAO (DAVAO DEL NORTE)|KAPALONG",
            "DAVAO (DAVAO DEL NORTE)|NEW CORELLA",
            "DAVAO (DAVAO DEL NORTE)|PANABO CITY",
            "DAVAO (DAVAO DEL NORTE)|SAN ISIDRO",
            "DAVAO (DAVAO DEL NORTE)|SANTO TOMAS",
            "DAVAO (DAVAO DEL NORTE)|TALAINGOD",
            "DAVAO DEL SUR|BANSALAN",
            "DAVAO DEL SUR|DAVAO CITY",
            "DAVAO DEL SUR|DIGOS CITY",
            "DAVAO DEL SUR|HAGONOY",
            "DAVAO DEL SUR|KIBLAWAN",
            "DAVAO DEL SUR|MAGSAYSAY",
            "DAVAO DEL SUR|MALALAG",
            "DAVAO DEL SUR|MATANAO",
            "DAVAO DEL SUR|PADADA",
            "DAVAO DEL SUR|SANTA CRUZ",
            "DAVAO DEL SUR|SULOP",
            "DAVAO OCCIDENTAL|DON MARCELINO",
            "DAVAO OCCIDENTAL|JOSE ABAD SANTOS (TRINIDAD)",
            "DAVAO OCCIDENTAL|MALITA",
            "DAVAO OCCIDENTAL|SANTA MARIA",
            "DAVAO OCCIDENTAL|SARANGANI",
            "DAVAO ORIENTAL|BAGANGA",
            "DAVAO ORIENTAL|BANAYBANAY",
            "DAVAO ORIENTAL|BOSTON",
            "DAVAO ORIENTAL|CARAGA",
            "DAVAO ORIENTAL|CATEEL",
            "DAVAO ORIENTAL|GOVERNOR GENEROSO",
            "DAVAO ORIENTAL|LUPON",
            "DAVAO ORIENTAL|MANAY",
            "DAVAO ORIENTAL|MATI CITY",
            "DAVAO ORIENTAL|SAN ISIDRO",
            "DAVAO ORIENTAL|TARRAGONA",
            "COTABATO (NORTH COT.)|ALAMADA",
            "COTABATO (NORTH COT.)|ALEOSAN",
            "COTABATO (NORTH COT.)|ANTIPAS",
            "COTABATO (NORTH COT.)|ARAKAN",
            "COTABATO (NORTH COT.)|BANISILAN",
            "COTABATO (NORTH COT.)|CARMEN",
            "COTABATO (NORTH COT.)|CITY OF KIDAPAWAN",
            "COTABATO (NORTH COT.)|KABACAN",
            "COTABATO (NORTH COT.)|LIBUNGAN",
            "COTABATO (NORTH COT.)|M'LANG",
            "COTABATO (NORTH COT.)|MAGPET",
            "COTABATO (NORTH COT.)|MAKILALA",
            "COTABATO (NORTH COT.)|MATALAM",
            "COTABATO (NORTH COT.)|MIDSAYAP",
            "COTABATO (NORTH COT.)|PIGKAWAYAN",
            "COTABATO (NORTH COT.)|PIKIT",
            "COTABATO (NORTH COT.)|PRESIDENT ROXAS",
            "COTABATO (NORTH COT.)|TULUNAN",
            "SARANGANI|ALABEL",
            "SARANGANI|GLAN",
            "SARANGANI|KIAMBA",
            "SARANGANI|MAASIM",
            "SARANGANI|MAITUM",
            "SARANGANI|MALAPATAN",
            "SARANGANI|MALUNGON",
            "SOUTH COTABATO|BANGA",
            "SOUTH COTABATO|GENERAL SANTOS CITY (DADIANGAS)",
            "SOUTH COTABATO|KORONADAL CITY",
            "SOUTH COTABATO|LAKE SEBU",
            "SOUTH COTABATO|NORALA",
            "SOUTH COTABATO|POLOMOLOK",
            "SOUTH COTABATO|SANTO NIÑO",
            "SOUTH COTABATO|SURALLAH",
            "SOUTH COTABATO|T`BOLI",
            "SOUTH COTABATO|TAMPAKAN",
            "SOUTH COTABATO|TANTANGAN",
            "SOUTH COTABATO|TUPI",
            "SULTAN KUDARAT|BAGUMBAYAN",
            "SULTAN KUDARAT|COLUMBIO",
            "SULTAN KUDARAT|ESPERANZA",
            "SULTAN KUDARAT|ISULAN",
            "SULTAN KUDARAT|KALAMANSIG",
            "SULTAN KUDARAT|LAMBAYONG (MARIANO MARCOS)",
            "SULTAN KUDARAT|LEBAK",
            "SULTAN KUDARAT|LUTAYAN",
            "SULTAN KUDARAT|PALIMBANG",
            "SULTAN KUDARAT|PRESIDENT QUIRINO",
            "SULTAN KUDARAT|SEN. NINOY AQUINO",
            "SULTAN KUDARAT|TACURONG CITY",
            "AGUSAN DEL NORTE|BUENAVISTA",
            "AGUSAN DEL NORTE|BUTUAN CITY",
            "AGUSAN DEL NORTE|CABADBARAN CITY",
            "AGUSAN DEL NORTE|CARMEN",
            "AGUSAN DEL NORTE|JABONGA",
            "AGUSAN DEL NORTE|KITCHARAO",
            "AGUSAN DEL NORTE|LAS NIEVES",
            "AGUSAN DEL NORTE|MAGALLANES",
            "AGUSAN DEL NORTE|NASIPIT",
            "AGUSAN DEL NORTE|REMEDIOS T. ROMUALDEZ",
            "AGUSAN DEL NORTE|SANTIAGO",
            "AGUSAN DEL NORTE|TUBAY",
            "AGUSAN DEL SUR|BAYUGAN CITY",
            "AGUSAN DEL SUR|BUNAWAN",
            "AGUSAN DEL SUR|ESPERANZA",
            "AGUSAN DEL SUR|LA PAZ",
            "AGUSAN DEL SUR|LORETO",
            "AGUSAN DEL SUR|PROSPERIDAD",
            "AGUSAN DEL SUR|ROSARIO",
            "AGUSAN DEL SUR|SAN FRANCISCO",
            "AGUSAN DEL SUR|SAN LUIS",
            "AGUSAN DEL SUR|SANTA JOSEFA",
            "AGUSAN DEL SUR|SIBAGAT",
            "AGUSAN DEL SUR|TALACOGON",
            "AGUSAN DEL SUR|TRENTO",
            "AGUSAN DEL SUR|VERUELA",
            "DINAGAT ISLANDS|BASILISA (RIZAL)",
            "DINAGAT ISLANDS|CAGDIANAO",
            "DINAGAT ISLANDS|DINAGAT",
            "DINAGAT ISLANDS|LIBJO (ALBOR)",
            "DINAGAT ISLANDS|LORETO",
            "DINAGAT ISLANDS|SAN JOSE",
            "DINAGAT ISLANDS|TUBAJON",
            "SURIGAO DEL NORTE|ALEGRIA",
            "SURIGAO DEL NORTE|BACUAG",
            "SURIGAO DEL NORTE|BURGOS",
            "SURIGAO DEL NORTE|CLAVER",
            "SURIGAO DEL NORTE|DAPA",
            "SURIGAO DEL NORTE|DEL CARMEN",
            "SURIGAO DEL NORTE|GENERAL LUNA",
            "SURIGAO DEL NORTE|GIGAQUIT",
            "SURIGAO DEL NORTE|MAINIT",
            "SURIGAO DEL NORTE|MALIMONO",
            "SURIGAO DEL NORTE|PILAR",
            "SURIGAO DEL NORTE|PLACER",
            "SURIGAO DEL NORTE|SAN BENITO",
            "SURIGAO DEL NORTE|SAN FRANCISCO (ANAO-AON)",
            "SURIGAO DEL NORTE|SAN ISIDRO",
            "SURIGAO DEL NORTE|SANTA MONICA (SAPAO)",
            "SURIGAO DEL NORTE|SISON",
            "SURIGAO DEL NORTE|SOCORRO",
            "SURIGAO DEL NORTE|SURIGAO CITY",
            "SURIGAO DEL NORTE|TAGANA-AN",
            "SURIGAO DEL NORTE|TUBOD",
            "SURIGAO DEL SUR|BAROBO",
            "SURIGAO DEL SUR|BAYABAS",
            "SURIGAO DEL SUR|BISLIG CITY",
            "SURIGAO DEL SUR|CAGWAIT",
            "SURIGAO DEL SUR|CANTILAN",
            "SURIGAO DEL SUR|CARMEN",
            "SURIGAO DEL SUR|CARRASCAL",
            "SURIGAO DEL SUR|CORTES",
            "SURIGAO DEL SUR|HINATUAN",
            "SURIGAO DEL SUR|LANUZA",
            "SURIGAO DEL SUR|LIANGA",
            "SURIGAO DEL SUR|LINGIG",
            "SURIGAO DEL SUR|MADRID",
            "SURIGAO DEL SUR|MARIHATAG",
            "SURIGAO DEL SUR|SAN AGUSTIN",
            "SURIGAO DEL SUR|SAN MIGUEL",
            "SURIGAO DEL SUR|TAGBINA",
            "SURIGAO DEL SUR|TAGO",
            "SURIGAO DEL SUR|TANDAG CITY",
            "ILOCOS NORTE|ADAMS",
            "ILOCOS NORTE|BACARRA",
            "ILOCOS NORTE|BADOC",
            "ILOCOS NORTE|BANGUI",
            "ILOCOS NORTE|BANNA (ESPIRITU)",
            "ILOCOS NORTE|BATAC CITY",
            "ILOCOS NORTE|BURGOS",
            "ILOCOS NORTE|CARASI",
            "ILOCOS NORTE|CURRIMAO",
            "ILOCOS NORTE|DINGRAS",
            "ILOCOS NORTE|DUMALNEG",
            "ILOCOS NORTE|LAOAG CITY",
            "ILOCOS NORTE|MARCOS",
            "ILOCOS NORTE|NUEVA ERA",
            "ILOCOS NORTE|PAGUDPUD",
            "ILOCOS NORTE|PAOAY",
            "ILOCOS NORTE|PASUQUIN",
            "ILOCOS NORTE|PIDDIG",
            "ILOCOS NORTE|PINILI",
            "ILOCOS NORTE|SAN NICOLAS",
            "ILOCOS NORTE|SARRAT",
            "ILOCOS NORTE|SOLSONA",
            "ILOCOS NORTE|VINTAR",
            "ILOCOS SUR|ALILEM",
            "ILOCOS SUR|BANAYOYO",
            "ILOCOS SUR|BANTAY",
            "ILOCOS SUR|BURGOS",
            "ILOCOS SUR|CABUGAO",
            "ILOCOS SUR|CANDON CITY",
            "ILOCOS SUR|CAOAYAN",
            "ILOCOS SUR|CERVANTES",
            "ILOCOS SUR|GALIMUYOD",
            "ILOCOS SUR|GREGORIO DEL PILAR (CONCEPCION)",
            "ILOCOS SUR|LIDLIDDA",
            "ILOCOS SUR|MAGSINGAL",
            "ILOCOS SUR|NAGBUKEL",
            "ILOCOS SUR|NARVACAN",
            "ILOCOS SUR|QUIRINO (ANGKAKI)",
            "ILOCOS SUR|SALCEDO (BAUGEN)",
            "ILOCOS SUR|SAN EMILIO",
            "ILOCOS SUR|SAN ESTEBAN",
            "ILOCOS SUR|SAN ILDEFONSO",
            "ILOCOS SUR|SAN JUAN (LAPOG)",
            "ILOCOS SUR|SAN VICENTE",
            "ILOCOS SUR|SANTA",
            "ILOCOS SUR|SANTA CATALINA",
            "ILOCOS SUR|SANTA CRUZ",
            "ILOCOS SUR|SANTA LUCIA",
            "ILOCOS SUR|SANTA MARIA",
            "ILOCOS SUR|SANTIAGO",
            "ILOCOS SUR|SANTO DOMINGO",
            "ILOCOS SUR|SIGAY",
            "ILOCOS SUR|SINAIT",
            "ILOCOS SUR|SUGPON",
            "ILOCOS SUR|SUYO",
            "ILOCOS SUR|TAGUDIN",
            "ILOCOS SUR|VIGAN CITY",
            "LA UNION|AGOO",
            "LA UNION|ARINGAY",
            "LA UNION|BACNOTAN",
            "LA UNION|BAGULIN",
            "LA UNION|BALAOAN",
            "LA UNION|BANGAR",
            "LA UNION|BAUANG",
            "LA UNION|BURGOS",
            "LA UNION|CABA",
            "LA UNION|CITY OF SAN FERNANDO",
            "LA UNION|LUNA",
            "LA UNION|NAGUILIAN",
            "LA UNION|PUGO",
            "LA UNION|ROSARIO",
            "LA UNION|SAN GABRIEL",
            "LA UNION|SAN JUAN",
            "LA UNION|SANTO TOMAS",
            "LA UNION|SANTOL",
            "LA UNION|SUDIPEN",
            "LA UNION|TUBAO",
            "PANGASINAN|AGNO",
            "PANGASINAN|AGUILAR",
            "PANGASINAN|ALAMINOS CITY",
            "PANGASINAN|ALCALA",
            "PANGASINAN|ANDA",
            "PANGASINAN|ASINGAN",
            "PANGASINAN|BALUNGAO",
            "PANGASINAN|BANI",
            "PANGASINAN|BASISTA",
            "PANGASINAN|BAUTISTA",
            "PANGASINAN|BAYAMBANG",
            "PANGASINAN|BINALONAN",
            "PANGASINAN|BINMALEY",
            "PANGASINAN|BOLINAO",
            "PANGASINAN|BUGALLON",
            "PANGASINAN|BURGOS",
            "PANGASINAN|CALASIAO",
            "PANGASINAN|DAGUPAN CITY",
            "PANGASINAN|DASOL",
            "PANGASINAN|INFANTA",
            "PANGASINAN|LABRADOR",
            "PANGASINAN|LAOAC",
            "PANGASINAN|LINGAYEN",
            "PANGASINAN|MABINI",
            "PANGASINAN|MALASIQUI",
            "PANGASINAN|MANAOAG",
            "PANGASINAN|MANGALDAN",
            "PANGASINAN|MANGATAREM",
            "PANGASINAN|MAPANDAN",
            "PANGASINAN|NATIVIDAD",
            "PANGASINAN|POZORRUBIO",
            "PANGASINAN|ROSALES",
            "PANGASINAN|SAN CARLOS CITY",
            "PANGASINAN|SAN FABIAN",
            "PANGASINAN|SAN JACINTO",
            "PANGASINAN|SAN MANUEL",
            "PANGASINAN|SAN NICOLAS",
            "PANGASINAN|SAN QUINTIN",
            "PANGASINAN|SANTA BARBARA",
            "PANGASINAN|SANTA MARIA",
            "PANGASINAN|SANTO TOMAS",
            "PANGASINAN|SISON",
            "PANGASINAN|SUAL",
            "PANGASINAN|TAYUG",
            "PANGASINAN|UMINGAN",
            "PANGASINAN|URBIZTONDO",
            "PANGASINAN|URDANETA CITY",
            "PANGASINAN|VILLASIS",
            "BATANES|BASCO",
            "BATANES|ITBAYAT",
            "BATANES|IVANA",
            "BATANES|MAHATAO",
            "BATANES|SABTANG",
            "BATANES|UYUGAN",
            "CAGAYAN|ABULUG",
            "CAGAYAN|ALCALA",
            "CAGAYAN|ALLACAPAN",
            "CAGAYAN|AMULUNG",
            "CAGAYAN|APARRI",
            "CAGAYAN|BAGGAO",
            "CAGAYAN|BALLESTEROS",
            "CAGAYAN|BUGUEY",
            "CAGAYAN|CALAYAN",
            "CAGAYAN|CAMALANIUGAN",
            "CAGAYAN|CLAVERIA",
            "CAGAYAN|ENRILE",
            "CAGAYAN|GATTARAN",
            "CAGAYAN|GONZAGA",
            "CAGAYAN|IGUIG",
            "CAGAYAN|LAL-LO",
            "CAGAYAN|LASAM",
            "CAGAYAN|PAMPLONA",
            "CAGAYAN|PEÑABLANCA",
            "CAGAYAN|PIAT",
            "CAGAYAN|RIZAL",
            "CAGAYAN|SANCHEZ-MIRA",
            "CAGAYAN|SANTA ANA",
            "CAGAYAN|SANTA PRAXEDES",
            "CAGAYAN|SANTA TERESITA",
            "CAGAYAN|SANTO NIÑO (FAIRE)",
            "CAGAYAN|SOLANA",
            "CAGAYAN|TUAO",
            "CAGAYAN|TUGUEGARAO CITY",
            "ISABELA|ALICIA",
            "ISABELA|ANGADANAN",
            "ISABELA|AURORA",
            "ISABELA|BENITO SOLIVEN",
            "ISABELA|BURGOS",
            "ISABELA|CABAGAN",
            "ISABELA|CABATUAN",
            "ISABELA|CAUAYAN CITY",
            "ISABELA|CITY OF SANTIAGO",
            "ISABELA|CORDON",
            "ISABELA|DELFIN ALBANO (MAGSAYSAY)",
            "ISABELA|DINAPIGUE",
            "ISABELA|DIVILACAN",
            "ISABELA|ECHAGUE",
            "ISABELA|GAMU",
            "ISABELA|ILAGAN CITY",
            "ISABELA|JONES",
            "ISABELA|LUNA",
            "ISABELA|MACONACON",
            "ISABELA|MALLIG",
            "ISABELA|NAGUILIAN",
            "ISABELA|PALANAN",
            "ISABELA|QUEZON",
            "ISABELA|QUIRINO",
            "ISABELA|RAMON",
            "ISABELA|REINA MERCEDES",
            "ISABELA|ROXAS",
            "ISABELA|SAN AGUSTIN",
            "ISABELA|SAN GUILLERMO",
            "ISABELA|SAN ISIDRO",
            "ISABELA|SAN MANUEL",
            "ISABELA|SAN MARIANO",
            "ISABELA|SAN MATEO",
            "ISABELA|SAN PABLO",
            "ISABELA|SANTA MARIA",
            "ISABELA|SANTO TOMAS",
            "ISABELA|TUMAUINI",
            "NUEVA VIZCAYA|ALFONSO CASTANEDA",
            "NUEVA VIZCAYA|AMBAGUIO",
            "NUEVA VIZCAYA|ARITAO",
            "NUEVA VIZCAYA|BAGABAG",
            "NUEVA VIZCAYA|BAMBANG",
            "NUEVA VIZCAYA|BAYOMBONG",
            "NUEVA VIZCAYA|DIADI",
            "NUEVA VIZCAYA|DUPAX DEL NORTE",
            "NUEVA VIZCAYA|DUPAX DEL SUR",
            "NUEVA VIZCAYA|KASIBU",
            "NUEVA VIZCAYA|KAYAPA",
            "NUEVA VIZCAYA|QUEZON",
            "NUEVA VIZCAYA|SANTA FE",
            "NUEVA VIZCAYA|SOLANO",
            "NUEVA VIZCAYA|VILLAVERDE",
            "QUIRINO|AGLIPAY",
            "QUIRINO|CABARROGUIS",
            "QUIRINO|DIFFUN",
            "QUIRINO|MADDELA",
            "QUIRINO|NAGTIPUNAN",
            "QUIRINO|SAGUDAY",
            "AURORA|BALER",
            "AURORA|CASIGURAN",
            "AURORA|DILASAG",
            "AURORA|DINALUNGAN",
            "AURORA|DINGALAN",
            "AURORA|DIPACULAO",
            "AURORA|MARIA AURORA",
            "AURORA|SAN LUIS",
            "BATAAN|ABUCAY",
            "BATAAN|BAGAC",
            "BATAAN|BALANGA CITY",
            "BATAAN|DINALUPIHAN",
            "BATAAN|HERMOSA",
            "BATAAN|LIMAY",
            "BATAAN|MARIVELES",
            "BATAAN|MORONG",
            "BATAAN|ORANI",
            "BATAAN|ORION",
            "BATAAN|PILAR",
            "BATAAN|SAMAL",
            "BULACAN|ANGAT",
            "BULACAN|BALAGTAS (BIGAA)",
            "BULACAN|BALIUAG",
            "BULACAN|BOCAUE",
            "BULACAN|BULACAN",
            "BULACAN|BUSTOS",
            "BULACAN|CALUMPIT",
            "BULACAN|DOÑA REMEDIOS TRINIDAD",
            "BULACAN|GUIGUINTO",
            "BULACAN|HAGONOY",
            "BULACAN|MALOLOS CITY",
            "BULACAN|MARILAO",
            "BULACAN|MEYCAUAYAN CITY",
            "BULACAN|NORZAGARAY",
            "BULACAN|OBANDO",
            "BULACAN|PANDI",
            "BULACAN|PAOMBONG",
            "BULACAN|PLARIDEL",
            "BULACAN|PULILAN",
            "BULACAN|SAN ILDEFONSO",
            "BULACAN|SAN JOSE DEL MONTE CITY",
            "BULACAN|SAN MIGUEL",
            "BULACAN|SAN RAFAEL",
            "BULACAN|SANTA MARIA",
            "NUEVA ECIJA|ALIAGA",
            "NUEVA ECIJA|BONGABON",
            "NUEVA ECIJA|CABANATUAN CITY",
            "NUEVA ECIJA|CABIAO",
            "NUEVA ECIJA|CARRANGLAN",
            "NUEVA ECIJA|CUYAPO",
            "NUEVA ECIJA|GABALDON (BITULOK AND SABANI)",
            "NUEVA ECIJA|GAPAN CITY",
            "NUEVA ECIJA|GENERAL MAMERTO NATIVIDAD",
            "NUEVA ECIJA|GENERAL TINIO (PAPAYA)",
            "NUEVA ECIJA|GUIMBA",
            "NUEVA ECIJA|JAEN",
            "NUEVA ECIJA|LAUR",
            "NUEVA ECIJA|LICAB",
            "NUEVA ECIJA|LLANERA",
            "NUEVA ECIJA|LUPAO",
            "NUEVA ECIJA|NAMPICUAN",
            "NUEVA ECIJA|PALAYAN CITY",
            "NUEVA ECIJA|PANTABANGAN",
            "NUEVA ECIJA|PEÑARANDA",
            "NUEVA ECIJA|QUEZON",
            "NUEVA ECIJA|RIZAL",
            "NUEVA ECIJA|SAN ANTONIO",
            "NUEVA ECIJA|SAN ISIDRO",
            "NUEVA ECIJA|SAN JOSE CITY",
            "NUEVA ECIJA|SAN LEONARDO",
            "NUEVA ECIJA|SANTA ROSA",
            "NUEVA ECIJA|SANTO DOMINGO",
            "NUEVA ECIJA|SCIENCE CITY OF MUÑOZ",
            "NUEVA ECIJA|TALAVERA",
            "NUEVA ECIJA|TALUGTUG",
            "NUEVA ECIJA|ZARAGOZA",
            "PAMPANGA|ANGELES CITY",
            "PAMPANGA|APALIT",
            "PAMPANGA|ARAYAT",
            "PAMPANGA|BACOLOR",
            "PAMPANGA|CANDABA",
            "PAMPANGA|FLORIDABLANCA",
            "PAMPANGA|GUAGUA",
            "PAMPANGA|LUBAO",
            "PAMPANGA|MABALACAT CITY",
            "PAMPANGA|MACABEBE",
            "PAMPANGA|MAGALANG",
            "PAMPANGA|MASANTOL",
            "PAMPANGA|MEXICO",
            "PAMPANGA|MINALIN",
            "PAMPANGA|PORAC",
            "PAMPANGA|SAN FERNANDO CITY",
            "PAMPANGA|SAN LUIS",
            "PAMPANGA|SAN SIMON",
            "PAMPANGA|SANTA ANA",
            "PAMPANGA|SANTA RITA",
            "PAMPANGA|SANTO TOMAS",
            "PAMPANGA|SASMUAN (SEXMOAN)",
            "TARLAC|ANAO",
            "TARLAC|BAMBAN",
            "TARLAC|CAMILING",
            "TARLAC|CAPAS",
            "TARLAC|CITY OF TARLAC",
            "TARLAC|CONCEPCION",
            "TARLAC|GERONA",
            "TARLAC|LA PAZ",
            "TARLAC|MAYANTOC",
            "TARLAC|MONCADA",
            "TARLAC|PANIQUI",
            "TARLAC|PURA",
            "TARLAC|RAMOS",
            "TARLAC|SAN CLEMENTE",
            "TARLAC|SAN JOSE",
            "TARLAC|SAN MANUEL",
            "TARLAC|SANTA IGNACIA",
            "TARLAC|VICTORIA",
            "ZAMBALES|BOTOLAN",
            "ZAMBALES|CABANGAN",
            "ZAMBALES|CANDELARIA",
            "ZAMBALES|CASTILLEJOS",
            "ZAMBALES|IBA",
            "ZAMBALES|MASINLOC",
            "ZAMBALES|OLONGAPO CITY",
            "ZAMBALES|PALAUIG",
            "ZAMBALES|SAN ANTONIO",
            "ZAMBALES|SAN FELIPE",
            "ZAMBALES|SAN MARCELINO",
            "ZAMBALES|SAN NARCISO",
            "ZAMBALES|SANTA CRUZ",
            "ZAMBALES|SUBIC",
            "BATANGAS|AGONCILLO",
            "BATANGAS|ALITAGTAG",
            "BATANGAS|BALAYAN",
            "BATANGAS|BALETE",
            "BATANGAS|BATANGAS CITY",
            "BATANGAS|BAUAN",
            "BATANGAS|CALACA",
            "BATANGAS|CALATAGAN",
            "BATANGAS|CUENCA",
            "BATANGAS|IBAAN",
            "BATANGAS|LAUREL",
            "BATANGAS|LEMERY",
            "BATANGAS|LIAN",
            "BATANGAS|LIPA CITY",
            "BATANGAS|LOBO",
            "BATANGAS|MABINI",
            "BATANGAS|MALVAR",
            "BATANGAS|MATAAS NA KAHOY",
            "BATANGAS|NASUGBU",
            "BATANGAS|PADRE GARCIA",
            "BATANGAS|ROSARIO",
            "BATANGAS|SAN JOSE",
            "BATANGAS|SAN JUAN",
            "BATANGAS|SAN LUIS",
            "BATANGAS|SAN NICOLAS",
            "BATANGAS|SAN PASCUAL",
            "BATANGAS|SANTA TERESITA",
            "BATANGAS|SANTO TOMAS",
            "BATANGAS|TAAL",
            "BATANGAS|TALISAY",
            "BATANGAS|TANAUAN CITY",
            "BATANGAS|TAYSAN",
            "BATANGAS|TINGLOY",
            "BATANGAS|TUY",
            "CAVITE|ALFONSO",
            "CAVITE|AMADEO",
            "CAVITE|BACOOR CITY",
            "CAVITE|CARMONA",
            "CAVITE|CAVITE CITY",
            "CAVITE|DASMARIÑAS CITY",
            "CAVITE|GEN. MARIANO ALVAREZ",
            "CAVITE|GENERAL EMILIO AGUINALDO",
            "CAVITE|GENERAL TRIAS CITY",
            "CAVITE|IMUS CITY",
            "CAVITE|INDANG",
            "CAVITE|KAWIT",
            "CAVITE|MAGALLANES",
            "CAVITE|MARAGONDON",
            "CAVITE|MENDEZ (MENDEZ-NUÑEZ)",
            "CAVITE|NAIC",
            "CAVITE|NOVELETA",
            "CAVITE|ROSARIO",
            "CAVITE|SILANG",
            "CAVITE|TAGAYTAY CITY",
            "CAVITE|TANZA",
            "CAVITE|TERNATE",
            "CAVITE|TRECE MARTIRES CITY",
            "LAGUNA|ALAMINOS",
            "LAGUNA|BAY",
            "LAGUNA|CABUYAO CITY",
            "LAGUNA|CALAMBA CITY",
            "LAGUNA|CALAUAN",
            "LAGUNA|CAVINTI",
            "LAGUNA|CITY OF BIÑAN",
            "LAGUNA|FAMY",
            "LAGUNA|KALAYAAN",
            "LAGUNA|LILIW",
            "LAGUNA|LOS BAÑOS",
            "LAGUNA|LUISIANA",
            "LAGUNA|LUMBAN",
            "LAGUNA|MABITAC",
            "LAGUNA|MAGDALENA",
            "LAGUNA|MAJAYJAY",
            "LAGUNA|NAGCARLAN",
            "LAGUNA|PAETE",
            "LAGUNA|PAGSANJAN",
            "LAGUNA|PAKIL",
            "LAGUNA|PANGIL",
            "LAGUNA|PILA",
            "LAGUNA|RIZAL",
            "LAGUNA|SAN PABLO CITY",
            "LAGUNA|SAN PEDRO CITY",
            "LAGUNA|SANTA CRUZ",
            "LAGUNA|SANTA MARIA",
            "LAGUNA|SANTA ROSA CITY",
            "LAGUNA|SINILOAN",
            "LAGUNA|VICTORIA",
            "QUEZON|AGDANGAN",
            "QUEZON|ALABAT",
            "QUEZON|ATIMONAN",
            "QUEZON|BUENAVISTA",
            "QUEZON|BURDEOS",
            "QUEZON|CALAUAG",
            "QUEZON|CANDELARIA",
            "QUEZON|CATANAUAN",
            "QUEZON|DOLORES",
            "QUEZON|GENERAL LUNA",
            "QUEZON|GENERAL NAKAR",
            "QUEZON|GUINAYANGAN",
            "QUEZON|GUMACA",
            "QUEZON|INFANTA",
            "QUEZON|JOMALIG",
            "QUEZON|LOPEZ",
            "QUEZON|LUCBAN",
            "QUEZON|LUCENA CITY",
            "QUEZON|MACALELON",
            "QUEZON|MAUBAN",
            "QUEZON|MULANAY",
            "QUEZON|PADRE BURGOS",
            "QUEZON|PAGBILAO",
            "QUEZON|PANUKULAN",
            "QUEZON|PATNANUNGAN",
            "QUEZON|PEREZ",
            "QUEZON|PITOGO",
            "QUEZON|PLARIDEL",
            "QUEZON|POLILLO",
            "QUEZON|QUEZON",
            "QUEZON|REAL",
            "QUEZON|SAMPALOC",
            "QUEZON|SAN ANDRES",
            "QUEZON|SAN ANTONIO",
            "QUEZON|SAN FRANCISCO (AURORA)",
            "QUEZON|SAN NARCISO",
            "QUEZON|SARIAYA",
            "QUEZON|TAGKAWAYAN",
            "QUEZON|TAYABAS CITY",
            "QUEZON|TIAONG",
            "QUEZON|UNISAN",
            "RIZAL|ANGONO",
            "RIZAL|BARAS",
            "RIZAL|BINANGONAN",
            "RIZAL|CAINTA",
            "RIZAL|CARDONA",
            "RIZAL|CITY OF ANTIPOLO",
            "RIZAL|JALA-JALA",
            "RIZAL|MORONG",
            "RIZAL|PILILLA",
            "RIZAL|RODRIGUEZ (MONTALBAN)",
            "RIZAL|SAN MATEO",
            "RIZAL|TANAY",
            "RIZAL|TAYTAY",
            "RIZAL|TERESA",
            "MARINDUQUE|BOAC",
            "MARINDUQUE|BUENAVISTA",
            "MARINDUQUE|GASAN",
            "MARINDUQUE|MOGPOG",
            "MARINDUQUE|SANTA CRUZ",
            "MARINDUQUE|TORRIJOS",
            "OCCIDENTAL MINDORO|ABRA DE ILOG",
            "OCCIDENTAL MINDORO|CALINTAAN",
            "OCCIDENTAL MINDORO|LOOC",
            "OCCIDENTAL MINDORO|LUBANG",
            "OCCIDENTAL MINDORO|MAGSAYSAY",
            "OCCIDENTAL MINDORO|MAMBURAO",
            "OCCIDENTAL MINDORO|PALUAN",
            "OCCIDENTAL MINDORO|RIZAL",
            "OCCIDENTAL MINDORO|SABLAYAN",
            "OCCIDENTAL MINDORO|SAN JOSE",
            "OCCIDENTAL MINDORO|SANTA CRUZ",
            "ORIENTAL MINDORO|BACO",
            "ORIENTAL MINDORO|BANSUD",
            "ORIENTAL MINDORO|BONGABONG",
            "ORIENTAL MINDORO|BULALACAO (SAN PEDRO)",
            "ORIENTAL MINDORO|CITY OF CALAPAN",
            "ORIENTAL MINDORO|GLORIA",
            "ORIENTAL MINDORO|MANSALAY",
            "ORIENTAL MINDORO|NAUJAN",
            "ORIENTAL MINDORO|PINAMALAYAN",
            "ORIENTAL MINDORO|POLA",
            "ORIENTAL MINDORO|PUERTO GALERA",
            "ORIENTAL MINDORO|ROXAS",
            "ORIENTAL MINDORO|SAN TEODORO",
            "ORIENTAL MINDORO|SOCORRO",
            "ORIENTAL MINDORO|VICTORIA",
            "PALAWAN|ABORLAN",
            "PALAWAN|AGUTAYA",
            "PALAWAN|ARACELI",
            "PALAWAN|BALABAC",
            "PALAWAN|BATARAZA",
            "PALAWAN|BROOKE'S POINT",
            "PALAWAN|BUSUANGA",
            "PALAWAN|CAGAYANCILLO",
            "PALAWAN|CORON",
            "PALAWAN|CULION",
            "PALAWAN|CUYO",
            "PALAWAN|DUMARAN",
            "PALAWAN|EL NIDO (BACUIT)",
            "PALAWAN|KALAYAAN",
            "PALAWAN|LINAPACAN",
            "PALAWAN|MAGSAYSAY",
            "PALAWAN|NARRA",
            "PALAWAN|PUERTO PRINCESA CITY",
            "PALAWAN|QUEZON",
            "PALAWAN|RIZAL (MARCOS)",
            "PALAWAN|ROXAS",
            "PALAWAN|SAN VICENTE",
            "PALAWAN|SOFRONIO ESPAÑOLA",
            "PALAWAN|TAYTAY",
            "ROMBLON|ALCANTARA",
            "ROMBLON|BANTON",
            "ROMBLON|CAJIDIOCAN",
            "ROMBLON|CALATRAVA",
            "ROMBLON|CONCEPCION",
            "ROMBLON|CORCUERA",
            "ROMBLON|FERROL",
            "ROMBLON|LOOC",
            "ROMBLON|MAGDIWANG",
            "ROMBLON|ODIONGAN",
            "ROMBLON|ROMBLON",
            "ROMBLON|SAN AGUSTIN",
            "ROMBLON|SAN ANDRES",
            "ROMBLON|SAN FERNANDO",
            "ROMBLON|SAN JOSE",
            "ROMBLON|SANTA FE",
            "ROMBLON|SANTA MARIA (IMELDA)",
            "ALBAY|BACACAY",
            "ALBAY|CAMALIG",
            "ALBAY|CITY OF LIGAO",
            "ALBAY|DARAGA (LOCSIN)",
            "ALBAY|GUINOBATAN",
            "ALBAY|JOVELLAR",
            "ALBAY|LEGAZPI CITY",
            "ALBAY|LIBON",
            "ALBAY|MALILIPOT",
            "ALBAY|MALINAO",
            "ALBAY|MANITO",
            "ALBAY|OAS",
            "ALBAY|PIO DURAN",
            "ALBAY|POLANGUI",
            "ALBAY|RAPU-RAPU",
            "ALBAY|SANTO DOMINGO (LIBOG)",
            "ALBAY|TABACO CITY",
            "ALBAY|TIWI",
            "CAMARINES NORTE|BASUD",
            "CAMARINES NORTE|CAPALONGA",
            "CAMARINES NORTE|DAET",
            "CAMARINES NORTE|JOSE PANGANIBAN",
            "CAMARINES NORTE|LABO",
            "CAMARINES NORTE|MERCEDES",
            "CAMARINES NORTE|PARACALE",
            "CAMARINES NORTE|SAN LORENZO RUIZ (IMELDA)",
            "CAMARINES NORTE|SAN VICENTE",
            "CAMARINES NORTE|SANTA ELENA",
            "CAMARINES NORTE|TALISAY",
            "CAMARINES NORTE|VINZONS",
            "CAMARINES SUR|BAAO",
            "CAMARINES SUR|BALATAN",
            "CAMARINES SUR|BATO",
            "CAMARINES SUR|BOMBON",
            "CAMARINES SUR|BUHI",
            "CAMARINES SUR|BULA",
            "CAMARINES SUR|CABUSAO",
            "CAMARINES SUR|CALABANGA",
            "CAMARINES SUR|CAMALIGAN",
            "CAMARINES SUR|CANAMAN",
            "CAMARINES SUR|CARAMOAN",
            "CAMARINES SUR|DEL GALLEGO",
            "CAMARINES SUR|GAINZA",
            "CAMARINES SUR|GARCHITORENA",
            "CAMARINES SUR|GOA",
            "CAMARINES SUR|IRIGA CITY",
            "CAMARINES SUR|LAGONOY",
            "CAMARINES SUR|LIBMANAN",
            "CAMARINES SUR|LUPI",
            "CAMARINES SUR|MAGARAO",
            "CAMARINES SUR|MILAOR",
            "CAMARINES SUR|MINALABAC",
            "CAMARINES SUR|NABUA",
            "CAMARINES SUR|NAGA CITY",
            "CAMARINES SUR|OCAMPO",
            "CAMARINES SUR|PAMPLONA",
            "CAMARINES SUR|PASACAO",
            "CAMARINES SUR|PILI",
            "CAMARINES SUR|PRESENTACION (PARUBCAN)",
            "CAMARINES SUR|RAGAY",
            "CAMARINES SUR|SAGÑAY",
            "CAMARINES SUR|SAN FERNANDO",
            "CAMARINES SUR|SAN JOSE",
            "CAMARINES SUR|SIPOCOT",
            "CAMARINES SUR|SIRUMA",
            "CAMARINES SUR|TIGAON",
            "CAMARINES SUR|TINAMBAC",
            "CATANDUANES|BAGAMANOC",
            "CATANDUANES|BARAS",
            "CATANDUANES|BATO",
            "CATANDUANES|CARAMORAN",
            "CATANDUANES|GIGMOTO",
            "CATANDUANES|PANDAN",
            "CATANDUANES|PANGANIBAN (PAYO)",
            "CATANDUANES|SAN ANDRES (CALOLBON)",
            "CATANDUANES|SAN MIGUEL",
            "CATANDUANES|VIGA",
            "CATANDUANES|VIRAC",
            "MASBATE|AROROY",
            "MASBATE|BALENO",
            "MASBATE|BALUD",
            "MASBATE|BATUAN",
            "MASBATE|CATAINGAN",
            "MASBATE|CAWAYAN",
            "MASBATE|CLAVERIA",
            "MASBATE|DIMASALANG",
            "MASBATE|ESPERANZA",
            "MASBATE|MANDAON",
            "MASBATE|MASBATE CITY",
            "MASBATE|MILAGROS",
            "MASBATE|MOBO",
            "MASBATE|MONREAL",
            "MASBATE|PALANAS",
            "MASBATE|PIO V. CORPUZ (LIMBUHAN)",
            "MASBATE|PLACER",
            "MASBATE|SAN FERNANDO",
            "MASBATE|SAN JACINTO",
            "MASBATE|SAN PASCUAL",
            "MASBATE|USON",
            "SORSOGON|BARCELONA",
            "SORSOGON|BULAN",
            "SORSOGON|BULUSAN",
            "SORSOGON|CASIGURAN",
            "SORSOGON|CASTILLA",
            "SORSOGON|DONSOL",
            "SORSOGON|GUBAT",
            "SORSOGON|IROSIN",
            "SORSOGON|JUBAN",
            "SORSOGON|MAGALLANES",
            "SORSOGON|MATNOG",
            "SORSOGON|PILAR",
            "SORSOGON|PRIETO DIAZ",
            "SORSOGON|SANTA MAGDALENA",
            "SORSOGON|SORSOGON CITY",
            "AKLAN|ALTAVAS",
            "AKLAN|BALETE",
            "AKLAN|BANGA",
            "AKLAN|BATAN",
            "AKLAN|BURUANGA",
            "AKLAN|IBAJAY",
            "AKLAN|KALIBO",
            "AKLAN|LEZO",
            "AKLAN|LIBACAO",
            "AKLAN|MADALAG",
            "AKLAN|MAKATO",
            "AKLAN|MALAY",
            "AKLAN|MALINAO",
            "AKLAN|NABAS",
            "AKLAN|NEW WASHINGTON",
            "AKLAN|NUMANCIA",
            "AKLAN|TANGALAN",
            "ANTIQUE|ANINI-Y",
            "ANTIQUE|BARBAZA",
            "ANTIQUE|BELISON",
            "ANTIQUE|BUGASONG",
            "ANTIQUE|CALUYA",
            "ANTIQUE|CULASI",
            "ANTIQUE|HAMTIC",
            "ANTIQUE|LAUA-AN",
            "ANTIQUE|LIBERTAD",
            "ANTIQUE|PANDAN",
            "ANTIQUE|PATNONGON",
            "ANTIQUE|SAN JOSE",
            "ANTIQUE|SAN REMIGIO",
            "ANTIQUE|SEBASTE",
            "ANTIQUE|SIBALOM",
            "ANTIQUE|TIBIAO",
            "ANTIQUE|TOBIAS FORNIER (DAO)",
            "ANTIQUE|VALDERRAMA",
            "CAPIZ|CUARTERO",
            "CAPIZ|DAO",
            "CAPIZ|DUMALAG",
            "CAPIZ|DUMARAO",
            "CAPIZ|IVISAN",
            "CAPIZ|JAMINDAN",
            "CAPIZ|MA-AYON",
            "CAPIZ|MAMBUSAO",
            "CAPIZ|PANAY",
            "CAPIZ|PANITAN",
            "CAPIZ|PILAR",
            "CAPIZ|PONTEVEDRA",
            "CAPIZ|PRESIDENT ROXAS",
            "CAPIZ|ROXAS CITY",
            "CAPIZ|SAPI-AN",
            "CAPIZ|SIGMA",
            "CAPIZ|TAPAZ",
            "GUIMARAS|BUENAVISTA",
            "GUIMARAS|JORDAN",
            "GUIMARAS|NUEVA VALENCIA",
            "GUIMARAS|SAN LORENZO",
            "GUIMARAS|SIBUNAG",
            "ILOILO|AJUY",
            "ILOILO|ALIMODIAN",
            "ILOILO|ANILAO",
            "ILOILO|BADIANGAN",
            "ILOILO|BALASAN",
            "ILOILO|BANATE",
            "ILOILO|BAROTAC NUEVO",
            "ILOILO|BAROTAC VIEJO",
            "ILOILO|BATAD",
            "ILOILO|BINGAWAN",
            "ILOILO|CABATUAN",
            "ILOILO|CALINOG",
            "ILOILO|CARLES",
            "ILOILO|CITY OF PASSI",
            "ILOILO|CONCEPCION",
            "ILOILO|DINGLE",
            "ILOILO|DUEÑAS",
            "ILOILO|DUMANGAS",
            "ILOILO|ESTANCIA",
            "ILOILO|GUIMBAL",
            "ILOILO|IGBARAS",
            "ILOILO|ILOILO CITY",
            "ILOILO|JANIUAY",
            "ILOILO|LAMBUNAO",
            "ILOILO|LEGANES",
            "ILOILO|LEMERY",
            "ILOILO|LEON",
            "ILOILO|MAASIN",
            "ILOILO|MIAGAO",
            "ILOILO|MINA",
            "ILOILO|NEW LUCENA",
            "ILOILO|OTON",
            "ILOILO|PAVIA",
            "ILOILO|POTOTAN",
            "ILOILO|SAN DIONISIO",
            "ILOILO|SAN ENRIQUE",
            "ILOILO|SAN JOAQUIN",
            "ILOILO|SAN MIGUEL",
            "ILOILO|SAN RAFAEL",
            "ILOILO|SANTA BARBARA",
            "ILOILO|SARA",
            "ILOILO|TIGBAUAN",
            "ILOILO|TUBUNGAN",
            "ILOILO|ZARRAGA",
            "NEGROS OCCIDENTAL|BACOLOD CITY",
            "NEGROS OCCIDENTAL|BAGO CITY",
            "NEGROS OCCIDENTAL|BINALBAGAN",
            "NEGROS OCCIDENTAL|CADIZ CITY",
            "NEGROS OCCIDENTAL|CALATRAVA",
            "NEGROS OCCIDENTAL|CANDONI",
            "NEGROS OCCIDENTAL|CAUAYAN",
            "NEGROS OCCIDENTAL|ENRIQUE B. MAGALONA (SARAVIA)",
            "NEGROS OCCIDENTAL|ESCALANTE CITY",
            "NEGROS OCCIDENTAL|HIMAMAYLAN CITY",
            "NEGROS OCCIDENTAL|HINIGARAN",
            "NEGROS OCCIDENTAL|HINOBA-AN (ASIA)",
            "NEGROS OCCIDENTAL|ILOG",
            "NEGROS OCCIDENTAL|ISABELA",
            "NEGROS OCCIDENTAL|KABANKALAN CITY",
            "NEGROS OCCIDENTAL|LA CARLOTA CITY",
            "NEGROS OCCIDENTAL|LA CASTELLANA",
            "NEGROS OCCIDENTAL|MANAPLA",
            "NEGROS OCCIDENTAL|MOISES PADILLA (MAGALLON)",
            "NEGROS OCCIDENTAL|MURCIA",
            "NEGROS OCCIDENTAL|PONTEVEDRA",
            "NEGROS OCCIDENTAL|PULUPANDAN",
            "NEGROS OCCIDENTAL|SAGAY CITY",
            "NEGROS OCCIDENTAL|SALVADOR BENEDICTO",
            "NEGROS OCCIDENTAL|SAN CARLOS CITY",
            "NEGROS OCCIDENTAL|SAN ENRIQUE",
            "NEGROS OCCIDENTAL|SILAY CITY",
            "NEGROS OCCIDENTAL|SIPALAY CITY",
            "NEGROS OCCIDENTAL|TALISAY CITY",
            "NEGROS OCCIDENTAL|TOBOSO",
            "NEGROS OCCIDENTAL|VALLADOLID",
            "NEGROS OCCIDENTAL|VICTORIAS CITY",
            "BOHOL|ALBURQUERQUE",
            "BOHOL|ALICIA",
            "BOHOL|ANDA",
            "BOHOL|ANTEQUERA",
            "BOHOL|BACLAYON",
            "BOHOL|BALILIHAN",
            "BOHOL|BATUAN",
            "BOHOL|BIEN UNIDO",
            "BOHOL|BILAR",
            "BOHOL|BUENAVISTA",
            "BOHOL|CALAPE",
            "BOHOL|CANDIJAY",
            "BOHOL|CARMEN",
            "BOHOL|CATIGBIAN",
            "BOHOL|CLARIN",
            "BOHOL|CORELLA",
            "BOHOL|CORTES",
            "BOHOL|DAGOHOY",
            "BOHOL|DANAO",
            "BOHOL|DAUIS",
            "BOHOL|DIMIAO",
            "BOHOL|DUERO",
            "BOHOL|GARCIA HERNANDEZ",
            "BOHOL|GUINDULMAN",
            "BOHOL|INABANGA",
            "BOHOL|JAGNA",
            "BOHOL|JETAFE",
            "BOHOL|LILA",
            "BOHOL|LOAY",
            "BOHOL|LOBOC",
            "BOHOL|LOON",
            "BOHOL|MABINI",
            "BOHOL|MARIBOJOC",
            "BOHOL|PANGLAO",
            "BOHOL|PILAR",
            "BOHOL|PRES. CARLOS P. GARCIA (PITOGO)",
            "BOHOL|SAGBAYAN (BORJA)",
            "BOHOL|SAN ISIDRO",
            "BOHOL|SAN MIGUEL",
            "BOHOL|SEVILLA",
            "BOHOL|SIERRA BULLONES",
            "BOHOL|SIKATUNA",
            "BOHOL|TAGBILARAN CITY",
            "BOHOL|TALIBON",
            "BOHOL|TRINIDAD",
            "BOHOL|TUBIGON",
            "BOHOL|UBAY",
            "BOHOL|VALENCIA",
            "CEBU|ALCANTARA",
            "CEBU|ALCOY",
            "CEBU|ALEGRIA",
            "CEBU|ALOGUINSAN",
            "CEBU|ARGAO",
            "CEBU|ASTURIAS",
            "CEBU|BADIAN",
            "CEBU|BALAMBAN",
            "CEBU|BANTAYAN",
            "CEBU|BARILI",
            "CEBU|BOGO CITY",
            "CEBU|BOLJOON",
            "CEBU|BORBON",
            "CEBU|CARCAR CITY",
            "CEBU|CARMEN",
            "CEBU|CATMON",
            "CEBU|CEBU CITY",
            "CEBU|COMPOSTELA",
            "CEBU|CONSOLACION",
            "CEBU|CORDOBA",
            "CEBU|DAANBANTAYAN",
            "CEBU|DALAGUETE",
            "CEBU|DANAO CITY",
            "CEBU|DUMANJUG",
            "CEBU|GINATILAN",
            "CEBU|LAPU-LAPU CITY (OPON)",
            "CEBU|LILOAN",
            "CEBU|MADRIDEJOS",
            "CEBU|MALABUYOC",
            "CEBU|MANDAUE CITY",
            "CEBU|MEDELLIN",
            "CEBU|MINGLANILLA",
            "CEBU|MOALBOAL",
            "CEBU|NAGA CITY",
            "CEBU|OSLOB",
            "CEBU|PILAR",
            "CEBU|PINAMUNGAHAN",
            "CEBU|PORO",
            "CEBU|RONDA",
            "CEBU|SAMBOAN",
            "CEBU|SAN FERNANDO",
            "CEBU|SAN FRANCISCO",
            "CEBU|SAN REMIGIO",
            "CEBU|SANTA FE",
            "CEBU|SANTANDER",
            "CEBU|SIBONGA",
            "CEBU|SOGOD",
            "CEBU|TABOGON",
            "CEBU|TABUELAN",
            "CEBU|TALISAY CITY",
            "CEBU|TOLEDO CITY",
            "CEBU|TUBURAN",
            "CEBU|TUDELA",
            "NEGROS ORIENTAL|AMLAN (AYUQUITAN)",
            "NEGROS ORIENTAL|AYUNGON",
            "NEGROS ORIENTAL|BACONG",
            "NEGROS ORIENTAL|BAIS CITY",
            "NEGROS ORIENTAL|BASAY",
            "NEGROS ORIENTAL|BAYAWAN CITY (TULONG)",
            "NEGROS ORIENTAL|BINDOY (PAYABON)",
            "NEGROS ORIENTAL|CANLAON CITY",
            "NEGROS ORIENTAL|DAUIN",
            "NEGROS ORIENTAL|DUMAGUETE CITY",
            "NEGROS ORIENTAL|GUIHULNGAN CITY",
            "NEGROS ORIENTAL|JIMALALUD",
            "NEGROS ORIENTAL|LA LIBERTAD",
            "NEGROS ORIENTAL|MABINAY",
            "NEGROS ORIENTAL|MANJUYOD",
            "NEGROS ORIENTAL|PAMPLONA",
            "NEGROS ORIENTAL|SAN JOSE",
            "NEGROS ORIENTAL|SANTA CATALINA",
            "NEGROS ORIENTAL|SIATON",
            "NEGROS ORIENTAL|SIBULAN",
            "NEGROS ORIENTAL|TANJAY CITY",
            "NEGROS ORIENTAL|TAYASAN",
            "NEGROS ORIENTAL|VALENCIA (LUZURRIAGA)",
            "NEGROS ORIENTAL|VALLEHERMOSO",
            "NEGROS ORIENTAL|ZAMBOANGUITA",
            "SIQUIJOR|ENRIQUE VILLANUEVA",
            "SIQUIJOR|LARENA",
            "SIQUIJOR|LAZI",
            "SIQUIJOR|MARIA",
            "SIQUIJOR|SAN JUAN",
            "SIQUIJOR|SIQUIJOR",
            "BILIRAN|ALMERIA",
            "BILIRAN|BILIRAN",
            "BILIRAN|CABUCGAYAN",
            "BILIRAN|CAIBIRAN",
            "BILIRAN|CULABA",
            "BILIRAN|KAWAYAN",
            "BILIRAN|MARIPIPI",
            "BILIRAN|NAVAL",
            "EASTERN SAMAR|ARTECHE",
            "EASTERN SAMAR|BALANGIGA",
            "EASTERN SAMAR|BALANGKAYAN",
            "EASTERN SAMAR|BORONGAN CITY",
            "EASTERN SAMAR|CAN-AVID",
            "EASTERN SAMAR|DOLORES",
            "EASTERN SAMAR|GENERAL MACARTHUR",
            "EASTERN SAMAR|GIPORLOS",
            "EASTERN SAMAR|GUIUAN",
            "EASTERN SAMAR|HERNANI",
            "EASTERN SAMAR|JIPAPAD",
            "EASTERN SAMAR|LAWAAN",
            "EASTERN SAMAR|LLORENTE",
            "EASTERN SAMAR|MASLOG",
            "EASTERN SAMAR|MAYDOLONG",
            "EASTERN SAMAR|MERCEDES",
            "EASTERN SAMAR|ORAS",
            "EASTERN SAMAR|QUINAPONDAN",
            "EASTERN SAMAR|SALCEDO",
            "EASTERN SAMAR|SAN JULIAN",
            "EASTERN SAMAR|SAN POLICARPO",
            "EASTERN SAMAR|SULAT",
            "EASTERN SAMAR|TAFT",
            "LEYTE|ABUYOG",
            "LEYTE|ALANGALANG",
            "LEYTE|ALBUERA",
            "LEYTE|BABATNGON",
            "LEYTE|BARUGO",
            "LEYTE|BATO",
            "LEYTE|BAYBAY CITY",
            "LEYTE|BURAUEN",
            "LEYTE|CALUBIAN",
            "LEYTE|CAPOOCAN",
            "LEYTE|CARIGARA",
            "LEYTE|DAGAMI",
            "LEYTE|DULAG",
            "LEYTE|HILONGOS",
            "LEYTE|HINDANG",
            "LEYTE|INOPACAN",
            "LEYTE|ISABEL",
            "LEYTE|JARO",
            "LEYTE|JAVIER (BUGHO)",
            "LEYTE|JULITA",
            "LEYTE|KANANGA",
            "LEYTE|LA PAZ",
            "LEYTE|LEYTE",
            "LEYTE|MACARTHUR",
            "LEYTE|MAHAPLAG",
            "LEYTE|MATAG-OB",
            "LEYTE|MATALOM",
            "LEYTE|MAYORGA",
            "LEYTE|MERIDA",
            "LEYTE|ORMOC CITY",
            "LEYTE|PALO",
            "LEYTE|PALOMPON",
            "LEYTE|PASTRANA",
            "LEYTE|SAN ISIDRO",
            "LEYTE|SAN MIGUEL",
            "LEYTE|SANTA FE",
            "LEYTE|TABANGO",
            "LEYTE|TABONTABON",
            "LEYTE|TACLOBAN CITY",
            "LEYTE|TANAUAN",
            "LEYTE|TOLOSA",
            "LEYTE|TUNGA",
            "LEYTE|VILLABA",
            "NORTHERN SAMAR|ALLEN",
            "NORTHERN SAMAR|BIRI",
            "NORTHERN SAMAR|BOBON",
            "NORTHERN SAMAR|CAPUL",
            "NORTHERN SAMAR|CATARMAN",
            "NORTHERN SAMAR|CATUBIG",
            "NORTHERN SAMAR|GAMAY",
            "NORTHERN SAMAR|LAOANG",
            "NORTHERN SAMAR|LAPINIG",
            "NORTHERN SAMAR|LAS NAVAS",
            "NORTHERN SAMAR|LAVEZARES",
            "NORTHERN SAMAR|LOPE DE VEGA",
            "NORTHERN SAMAR|MAPANAS",
            "NORTHERN SAMAR|MONDRAGON",
            "NORTHERN SAMAR|PALAPAG",
            "NORTHERN SAMAR|PAMBUJAN",
            "NORTHERN SAMAR|ROSARIO",
            "NORTHERN SAMAR|SAN ANTONIO",
            "NORTHERN SAMAR|SAN ISIDRO",
            "NORTHERN SAMAR|SAN JOSE",
            "NORTHERN SAMAR|SAN ROQUE",
            "NORTHERN SAMAR|SAN VICENTE",
            "NORTHERN SAMAR|SILVINO LOBOS",
            "NORTHERN SAMAR|VICTORIA",
            "SAMAR (WESTERN SAMAR)|ALMAGRO",
            "SAMAR (WESTERN SAMAR)|BASEY",
            "SAMAR (WESTERN SAMAR)|CALBAYOG CITY",
            "SAMAR (WESTERN SAMAR)|CALBIGA",
            "SAMAR (WESTERN SAMAR)|CATBALOGAN CITY",
            "SAMAR (WESTERN SAMAR)|DARAM",
            "SAMAR (WESTERN SAMAR)|GANDARA",
            "SAMAR (WESTERN SAMAR)|HINABANGAN",
            "SAMAR (WESTERN SAMAR)|JIABONG",
            "SAMAR (WESTERN SAMAR)|MARABUT",
            "SAMAR (WESTERN SAMAR)|MATUGUINAO",
            "SAMAR (WESTERN SAMAR)|MOTIONG",
            "SAMAR (WESTERN SAMAR)|PAGSANGHAN",
            "SAMAR (WESTERN SAMAR)|PARANAS (WRIGHT)",
            "SAMAR (WESTERN SAMAR)|PINABACDAO",
            "SAMAR (WESTERN SAMAR)|SAN JORGE",
            "SAMAR (WESTERN SAMAR)|SAN JOSE DE BUAN",
            "SAMAR (WESTERN SAMAR)|SAN SEBASTIAN",
            "SAMAR (WESTERN SAMAR)|SANTA MARGARITA",
            "SAMAR (WESTERN SAMAR)|SANTA RITA",
            "SAMAR (WESTERN SAMAR)|SANTO NIÑO",
            "SAMAR (WESTERN SAMAR)|TAGAPUL-AN",
            "SAMAR (WESTERN SAMAR)|TALALORA",
            "SAMAR (WESTERN SAMAR)|TARANGNAN",
            "SAMAR (WESTERN SAMAR)|VILLAREAL",
            "SAMAR (WESTERN SAMAR)|ZUMARRAGA",
            "SOUTHERN LEYTE|ANAHAWAN",
            "SOUTHERN LEYTE|BONTOC",
            "SOUTHERN LEYTE|HINUNANGAN",
            "SOUTHERN LEYTE|HINUNDAYAN",
            "SOUTHERN LEYTE|LIBAGON",
            "SOUTHERN LEYTE|LILOAN",
            "SOUTHERN LEYTE|LIMASAWA",
            "SOUTHERN LEYTE|MAASIN CITY",
            "SOUTHERN LEYTE|MACROHON",
            "SOUTHERN LEYTE|MALITBOG",
            "SOUTHERN LEYTE|PADRE BURGOS",
            "SOUTHERN LEYTE|PINTUYAN",
            "SOUTHERN LEYTE|SAINT BERNARD",
            "SOUTHERN LEYTE|SAN FRANCISCO",
            "SOUTHERN LEYTE|SAN JUAN (CABALIAN)",
            "SOUTHERN LEYTE|SAN RICARDO",
            "SOUTHERN LEYTE|SILAGO",
            "SOUTHERN LEYTE|SOGOD",
            "SOUTHERN LEYTE|TOMAS OPPUS",
            "ZAMBOANGA DEL NORTE|BACUNGAN (LEON T. POSTIGO)",
            "ZAMBOANGA DEL NORTE|BALIGUIAN",
            "ZAMBOANGA DEL NORTE|DAPITAN CITY",
            "ZAMBOANGA DEL NORTE|DIPOLOG CITY",
            "ZAMBOANGA DEL NORTE|GODOD",
            "ZAMBOANGA DEL NORTE|GUTALAC",
            "ZAMBOANGA DEL NORTE|JOSE DALMAN (PONOT)",
            "ZAMBOANGA DEL NORTE|KALAWIT",
            "ZAMBOANGA DEL NORTE|KATIPUNAN",
            "ZAMBOANGA DEL NORTE|LA LIBERTAD",
            "ZAMBOANGA DEL NORTE|LABASON",
            "ZAMBOANGA DEL NORTE|LILOY",
            "ZAMBOANGA DEL NORTE|MANUKAN",
            "ZAMBOANGA DEL NORTE|MUTIA",
            "ZAMBOANGA DEL NORTE|PIÑAN (NEW PIÑAN)",
            "ZAMBOANGA DEL NORTE|POLANCO",
            "ZAMBOANGA DEL NORTE|PRES. MANUEL A. ROXAS",
            "ZAMBOANGA DEL NORTE|RIZAL",
            "ZAMBOANGA DEL NORTE|SALUG",
            "ZAMBOANGA DEL NORTE|SERGIO OSMEÑA SR.",
            "ZAMBOANGA DEL NORTE|SIAYAN",
            "ZAMBOANGA DEL NORTE|SIBUCO",
            "ZAMBOANGA DEL NORTE|SIBUTAD",
            "ZAMBOANGA DEL NORTE|SINDANGAN",
            "ZAMBOANGA DEL NORTE|SIOCON",
            "ZAMBOANGA DEL NORTE|SIRAWAI",
            "ZAMBOANGA DEL NORTE|TAMPILISAN",
            "ZAMBOANGA DEL SUR|AURORA",
            "ZAMBOANGA DEL SUR|BAYOG",
            "ZAMBOANGA DEL SUR|DIMATALING",
            "ZAMBOANGA DEL SUR|DINAS",
            "ZAMBOANGA DEL SUR|DUMALINAO",
            "ZAMBOANGA DEL SUR|DUMINGAG",
            "ZAMBOANGA DEL SUR|GUIPOS",
            "ZAMBOANGA DEL SUR|JOSEFINA",
            "ZAMBOANGA DEL SUR|KUMALARANG",
            "ZAMBOANGA DEL SUR|LABANGAN",
            "ZAMBOANGA DEL SUR|LAKEWOOD",
            "ZAMBOANGA DEL SUR|LAPUYAN",
            "ZAMBOANGA DEL SUR|MAHAYAG",
            "ZAMBOANGA DEL SUR|MARGOSATUBIG",
            "ZAMBOANGA DEL SUR|MIDSALIP",
            "ZAMBOANGA DEL SUR|MOLAVE",
            "ZAMBOANGA DEL SUR|PAGADIAN CITY",
            "ZAMBOANGA DEL SUR|PITOGO",
            "ZAMBOANGA DEL SUR|RAMON MAGSAYSAY (LIARGO)",
            "ZAMBOANGA DEL SUR|SAN MIGUEL",
            "ZAMBOANGA DEL SUR|SAN PABLO",
            "ZAMBOANGA DEL SUR|SOMINOT (DON MARIANO MARCOS)",
            "ZAMBOANGA DEL SUR|TABINA",
            "ZAMBOANGA DEL SUR|TAMBULIG",
            "ZAMBOANGA DEL SUR|TIGBAO",
            "ZAMBOANGA DEL SUR|TUKURAN",
            "ZAMBOANGA DEL SUR|VINCENZO A. SAGUN",
            "ZAMBOANGA DEL SUR|ZAMBOANGA CITY",
            "ZAMBOANGA SIBUGAY|ALICIA",
            "ZAMBOANGA SIBUGAY|BUUG",
            "ZAMBOANGA SIBUGAY|DIPLAHAN",
            "ZAMBOANGA SIBUGAY|IMELDA",
            "ZAMBOANGA SIBUGAY|IPIL",
            "ZAMBOANGA SIBUGAY|KABASALAN",
            "ZAMBOANGA SIBUGAY|MABUHAY",
            "ZAMBOANGA SIBUGAY|MALANGAS",
            "ZAMBOANGA SIBUGAY|NAGA",
            "ZAMBOANGA SIBUGAY|OLUTANGA",
            "ZAMBOANGA SIBUGAY|PAYAO",
            "ZAMBOANGA SIBUGAY|ROSELLER LIM",
            "ZAMBOANGA SIBUGAY|SIAY",
            "ZAMBOANGA SIBUGAY|TALUSAN",
            "ZAMBOANGA SIBUGAY|TITAY",
            "ZAMBOANGA SIBUGAY|TUNGAWAN",
            "BASILAN|AKBAR",
            "BASILAN|AL-BARKA",
            "BASILAN|HADJI MOHAMMAD AJUL",
            "BASILAN|HADJI MUHTAMAD",
            "BASILAN|ISABELA CITY",
            "BASILAN|LAMITAN CITY",
            "BASILAN|LANTAWAN",
            "BASILAN|MALUSO",
            "BASILAN|SUMISIP",
            "BASILAN|TABUAN-LASA",
            "BASILAN|TIPO-TIPO",
            "BASILAN|TUBURAN",
            "BASILAN|UNGKAYA PUKAN",
            "LANAO DEL SUR|AMAI MANABILANG (BUMBARAN)",
            "LANAO DEL SUR|BACOLOD-KALAWI (BACOLOD GRANDE)",
            "LANAO DEL SUR|BALABAGAN",
            "LANAO DEL SUR|BALINDONG (WATU)",
            "LANAO DEL SUR|BAYANG",
            "LANAO DEL SUR|BINIDAYAN",
            "LANAO DEL SUR|BUADIPOSO-BUNTONG",
            "LANAO DEL SUR|BUBONG",
            "LANAO DEL SUR|BUTIG",
            "LANAO DEL SUR|CALANOGAS",
            "LANAO DEL SUR|DITSAAN-RAMAIN",
            "LANAO DEL SUR|GANASSI",
            "LANAO DEL SUR|KAPAI",
            "LANAO DEL SUR|KAPATAGAN",
            "LANAO DEL SUR|LUMBA-BAYABAO (MAGUING)",
            "LANAO DEL SUR|LUMBACA-UNAYAN",
            "LANAO DEL SUR|LUMBATAN",
            "LANAO DEL SUR|LUMBAYANAGUE",
            "LANAO DEL SUR|MADALUM",
            "LANAO DEL SUR|MADAMBA",
            "LANAO DEL SUR|MAGUING",
            "LANAO DEL SUR|MALABANG",
            "LANAO DEL SUR|MARANTAO",
            "LANAO DEL SUR|MARAWI CITY",
            "LANAO DEL SUR|MAROGONG",
            "LANAO DEL SUR|MASIU",
            "LANAO DEL SUR|MULONDO",
            "LANAO DEL SUR|PAGAYAWAN (TATARIKAN)",
            "LANAO DEL SUR|PIAGAPO",
            "LANAO DEL SUR|PICONG (SULTAN GUMANDER)",
            "LANAO DEL SUR|POONA BAYABAO (GATA)",
            "LANAO DEL SUR|PUALAS",
            "LANAO DEL SUR|SAGUIARAN",
            "LANAO DEL SUR|SULTAN DUMALONDONG",
            "LANAO DEL SUR|TAGOLOAN",
            "LANAO DEL SUR|TAMPARAN",
            "LANAO DEL SUR|TARAKA",
            "LANAO DEL SUR|TUBARAN",
            "LANAO DEL SUR|TUGAYA",
            "LANAO DEL SUR|WAO",
            "MAGUINDANAO|AMPATUAN",
            "MAGUINDANAO|BARIRA",
            "MAGUINDANAO|BULDON",
            "MAGUINDANAO|BULUAN",
            "MAGUINDANAO|COTABATO CITY",
            "MAGUINDANAO|DATU ABDULLAH SANGKI",
            "MAGUINDANAO|DATU ANGGAL MIDTIMBANG",
            "MAGUINDANAO|DATU BLAH T. SINSUAT",
            "MAGUINDANAO|DATU HOFFER AMPATUAN",
            "MAGUINDANAO|DATU ODIN SINSUAT (DINAIG)",
            "MAGUINDANAO|DATU PAGLAS",
            "MAGUINDANAO|DATU PIANG",
            "MAGUINDANAO|DATU SALIBO",
            "MAGUINDANAO|DATU SAUDI AMPATUAN",
            "MAGUINDANAO|DATU UNSAY",
            "MAGUINDANAO|GEN. S. K. PENDATUN",
            "MAGUINDANAO|GUINDULUNGAN",
            "MAGUINDANAO|KABUNTALAN (TUMBAO)",
            "MAGUINDANAO|MAMASAPANO",
            "MAGUINDANAO|MANGUDADATU",
            "MAGUINDANAO|MATANOG",
            "MAGUINDANAO|NORTHERN KABUNTALAN",
            "MAGUINDANAO|PAGAGAWAN",
            "MAGUINDANAO|PAGALUNGAN",
            "MAGUINDANAO|PAGLAT",
            "MAGUINDANAO|PANDAG",
            "MAGUINDANAO|PARANG",
            "MAGUINDANAO|RAJAH BUAYAN",
            "MAGUINDANAO|SHARIFF AGUAK (MAGANOY)",
            "MAGUINDANAO|SHARIFF SAYDONA MUSTAPHA",
            "MAGUINDANAO|SOUTH UPI",
            "MAGUINDANAO|SULTAN KUDARAT (NULING)",
            "MAGUINDANAO|SULTAN MASTURA",
            "MAGUINDANAO|SULTAN SA BARONGIS (LAMBAYONG)",
            "MAGUINDANAO|TALAYAN",
            "MAGUINDANAO|TALITAY",
            "MAGUINDANAO|UPI",
            "SULU|HADJI PANGLIMA TAHIL (MARUNGGAS)",
            "SULU|INDANAN",
            "SULU|JOLO",
            "SULU|KALINGALAN CALUANG",
            "SULU|LUGUS",
            "SULU|LUUK",
            "SULU|MAIMBUNG",
            "SULU|OLD PANAMAO",
            "SULU|OMAR",
            "SULU|PANDAMI",
            "SULU|PANGLIMA ESTINO (NEW PANAMAO)",
            "SULU|PANGUTARAN",
            "SULU|PARANG",
            "SULU|PATA",
            "SULU|PATIKUL",
            "SULU|SIASI",
            "SULU|TALIPAO",
            "SULU|TAPUL",
            "SULU|TONGKIL",
            "TAWI-TAWI|BONGAO",
            "TAWI-TAWI|LANGUYAN",
            "TAWI-TAWI|MAPUN (CAGAYAN DE TAWI-TAWI)",
            "TAWI-TAWI|PANGLIMA SUGALA (BALIMBING)",
            "TAWI-TAWI|SAPA-SAPA",
            "TAWI-TAWI|SIBUTU",
            "TAWI-TAWI|SIMUNUL",
            "TAWI-TAWI|SITANGKAI",
            "TAWI-TAWI|SOUTH UBIAN",
            "TAWI-TAWI|TANDUBAS",
            "TAWI-TAWI|TURTLE ISLANDS",
            "ABRA|BANGUED",
            "ABRA|BOLINEY",
            "ABRA|BUCAY",
            "ABRA|BUCLOC",
            "ABRA|DAGUIOMAN",
            "ABRA|DANGLAS",
            "ABRA|DOLORES",
            "ABRA|LA PAZ",
            "ABRA|LACUB",
            "ABRA|LAGANGILANG",
            "ABRA|LAGAYAN",
            "ABRA|LANGIDEN",
            "ABRA|LICUAN-BAAY (LICUAN)",
            "ABRA|LUBA",
            "ABRA|MALIBCONG",
            "ABRA|MANABO",
            "ABRA|PEÑARRUBIA",
            "ABRA|PIDIGAN",
            "ABRA|PILAR",
            "ABRA|SALLAPADAN",
            "ABRA|SAN ISIDRO",
            "ABRA|SAN JUAN",
            "ABRA|SAN QUINTIN",
            "ABRA|TAYUM",
            "ABRA|TINEG",
            "ABRA|TUBO",
            "ABRA|VILLAVICIOSA",
            "APAYAO|CALANASAN (BAYAG)",
            "APAYAO|CONNER",
            "APAYAO|FLORA",
            "APAYAO|KABUGAO",
            "APAYAO|LUNA",
            "APAYAO|PUDTOL",
            "APAYAO|SANTA MARCELA",
            "BENGUET|ATOK",
            "BENGUET|BAGUIO CITY",
            "BENGUET|BAKUN",
            "BENGUET|BOKOD",
            "BENGUET|BUGUIAS",
            "BENGUET|ITOGON",
            "BENGUET|KABAYAN",
            "BENGUET|KAPANGAN",
            "BENGUET|KIBUNGAN",
            "BENGUET|LA TRINIDAD",
            "BENGUET|MANKAYAN",
            "BENGUET|SABLAN",
            "BENGUET|TUBA",
            "BENGUET|TUBLAY",
            "IFUGAO|AGUINALDO",
            "IFUGAO|ALFONSO LISTA (POTIA)",
            "IFUGAO|ASIPULO",
            "IFUGAO|BANAUE",
            "IFUGAO|HINGYON",
            "IFUGAO|HUNGDUAN",
            "IFUGAO|KIANGAN",
            "IFUGAO|LAGAWE",
            "IFUGAO|LAMUT",
            "IFUGAO|MAYOYAO",
            "IFUGAO|TINOC",
            "KALINGA|BALBALAN",
            "KALINGA|LUBUAGAN",
            "KALINGA|PASIL",
            "KALINGA|PINUKPUK",
            "KALINGA|RIZAL (LIWAN)",
            "KALINGA|TABUK CITY",
            "KALINGA|TANUDAN",
            "KALINGA|TINGLAYAN",
            "MOUNTAIN PROVINCE|BARLIG",
            "MOUNTAIN PROVINCE|BAUKO",
            "MOUNTAIN PROVINCE|BESAO",
            "MOUNTAIN PROVINCE|BONTOC",
            "MOUNTAIN PROVINCE|NATONIN",
            "MOUNTAIN PROVINCE|PARACELIS",
            "MOUNTAIN PROVINCE|SABANGAN",
            "MOUNTAIN PROVINCE|SADANGA",
            "MOUNTAIN PROVINCE|SAGADA",
            "MOUNTAIN PROVINCE|TADIAN",
            "NATIONAL CAPITAL REGION - FOURTH DISTRICT|CITY OF LAS PIÑAS",
            "NATIONAL CAPITAL REGION - FOURTH DISTRICT|CITY OF MAKATI",
            "NATIONAL CAPITAL REGION - FOURTH DISTRICT|CITY OF MUNTINLUPA",
            "NATIONAL CAPITAL REGION - FOURTH DISTRICT|CITY OF PARAÑAQUE",
            "NATIONAL CAPITAL REGION - FOURTH DISTRICT|PASAY CITY",
            "NATIONAL CAPITAL REGION - MANILA|BINONDO",
            "NATIONAL CAPITAL REGION - MANILA|ERMITA",
            "NATIONAL CAPITAL REGION - MANILA|INTRAMUROS",
            "NATIONAL CAPITAL REGION - MANILA|MALATE",
            "NATIONAL CAPITAL REGION - MANILA|PACO",
            "NATIONAL CAPITAL REGION - MANILA|PANDACAN",
            "NATIONAL CAPITAL REGION - MANILA|PORT AREA",
            "NATIONAL CAPITAL REGION - MANILA|QUIAPO",
            "NATIONAL CAPITAL REGION - MANILA|SAMPALOC",
            "NATIONAL CAPITAL REGION - MANILA|SAN MIGUEL",
            "NATIONAL CAPITAL REGION - MANILA|SAN NICOLAS",
            "NATIONAL CAPITAL REGION - MANILA|SANTA ANA",
            "NATIONAL CAPITAL REGION - MANILA|SANTA CRUZ",
            "NATIONAL CAPITAL REGION - MANILA|TONDO",
            "NATIONAL CAPITAL REGION - SECOND DISTRICT|CITY OF MANDALUYONG",
            "NATIONAL CAPITAL REGION - SECOND DISTRICT|CITY OF MARIKINA",
            "NATIONAL CAPITAL REGION - SECOND DISTRICT|CITY OF PASIG",
            "NATIONAL CAPITAL REGION - SECOND DISTRICT|QUEZON CITY",
            "NATIONAL CAPITAL REGION - SECOND DISTRICT|SAN JUAN CITY",
            "NATIONAL CAPITAL REGION - THIRD DISTRICT|CALOOCAN CITY",
            "NATIONAL CAPITAL REGION - THIRD DISTRICT|CITY OF VALENZUELA",
            "NATIONAL CAPITAL REGION - THIRD DISTRICT|MALABON CITY",
            "NATIONAL CAPITAL REGION - THIRD DISTRICT|NAVOTAS CITY",
            "TAGUIG - PATEROS|PATEROS",
            "TAGUIG - PATEROS|TAGUIG",
    };
}
