package com.atpuser.Database.Stubs;

public class SurigaoBarangayStub {
    public static String[] BARANGAYS = {
            "BUENAVISTA|ABILAN",
            "BUENAVISTA|AGONG-ONG",
            "BUENAVISTA|ALUBIJID",
            "BUENAVISTA|GUINABSAN",
            "BUENAVISTA|LOWER OLAVE",
            "BUENAVISTA|MACALANG",
            "BUENAVISTA|MALAPONG",
            "BUENAVISTA|MALPOC",
            "BUENAVISTA|MANAPA",
            "BUENAVISTA|MATABAO",
            "BUENAVISTA|POBLACION 1",
            "BUENAVISTA|POBLACION 2",
            "BUENAVISTA|POBLACION 3",
            "BUENAVISTA|POBLACION 4",
            "BUENAVISTA|POBLACION 5",
            "BUENAVISTA|POBLACION 6",
            "BUENAVISTA|POBLACION 7",
            "BUENAVISTA|POBLACION 8",
            "BUENAVISTA|POBLACION 9",
            "BUENAVISTA|POBLACION 10",
            "BUENAVISTA|RIZAL",
            "BUENAVISTA|SACOL",
            "BUENAVISTA|SANGAY",
            "BUENAVISTA|SIMBALAN",
            "BUENAVISTA|TALO-AO",
            "BUTUAN CITY|AGAO POB. (BGY. 3)",
            "BUTUAN CITY|AGUSAN PEQUEÑO",
            "BUTUAN CITY|AMBAGO",
            "BUTUAN CITY|AMPARO",
            "BUTUAN CITY|AMPAYON",
            "BUTUAN CITY|ANTICALA",
            "BUTUAN CITY|ANTONGALON",
            "BUTUAN CITY|AUPAGAN",
            "BUTUAN CITY|BAAN KM 3",
            "BUTUAN CITY|BAAN RIVERSIDE POB. (BGY. 20)",
            "BUTUAN CITY|BABAG",
            "BUTUAN CITY|BADING POB. (BGY. 22)",
            "BUTUAN CITY|BANCASI",
            "BUTUAN CITY|BANZA",
            "BUTUAN CITY|BAOBAOAN",
            "BUTUAN CITY|BASAG",
            "BUTUAN CITY|BAYANIHAN POB. (BGY. 27)",
            "BUTUAN CITY|BILAY",
            "BUTUAN CITY|BIT-OS",
            "BUTUAN CITY|BITAN-AGAN",
            "BUTUAN CITY|BOBON",
            "BUTUAN CITY|BONBON",
            "BUTUAN CITY|BUGABUS",
            "BUTUAN CITY|BUGSUKAN",
            "BUTUAN CITY|BUHANGIN POB. (BGY. 19)",
            "BUTUAN CITY|CABCABON",
            "BUTUAN CITY|CAMAYAHAN",
            "BUTUAN CITY|DAGOHOY POB. (BGY. 7)",
            "BUTUAN CITY|DANKIAS",
            "BUTUAN CITY|DE ORO",
            "BUTUAN CITY|DIEGO SILANG POB. (BGY. 6)",
            "BUTUAN CITY|DON FRANCISCO",
            "BUTUAN CITY|DOONGAN",
            "BUTUAN CITY|DULAG",
            "BUTUAN CITY|DUMALAGAN",
            "BUTUAN CITY|FLORIDA",
            "BUTUAN CITY|GOLDEN RIBBON POB. (BGY. 2)",
            "BUTUAN CITY|HOLY REDEEMER POB. (BGY. 23)",
            "BUTUAN CITY|HUMABON POB. (BGY. 11)",
            "BUTUAN CITY|IMADEJAS POB. (BGY. 24)",
            "BUTUAN CITY|JOSE RIZAL POB. (BGY. 25)",
            "BUTUAN CITY|KINAMLUTAN",
            "BUTUAN CITY|LAPU-LAPU POB. (BGY. 8)",
            "BUTUAN CITY|LEMON",
            "BUTUAN CITY|LEON KILAT POB. (BGY. 13)",
            "BUTUAN CITY|LIBERTAD",
            "BUTUAN CITY|LIMAHA POB. (BGY. 14)",
            "BUTUAN CITY|LOS ANGELES",
            "BUTUAN CITY|LUMBOCAN",
            "BUTUAN CITY|MAGUINDA",
            "BUTUAN CITY|MAHAY",
            "BUTUAN CITY|MAHOGANY POB. (BGY. 21)",
            "BUTUAN CITY|MAIBU",
            "BUTUAN CITY|MANDAMO",
            "BUTUAN CITY|MANILA DE BUGABUS",
            "BUTUAN CITY|MAON POB. (BGY. 1)",
            "BUTUAN CITY|MASAO",
            "BUTUAN CITY|MAUG",
            "BUTUAN CITY|NEW SOCIETY VILLAGE POB. (BGY. 26)",
            "BUTUAN CITY|NONG-NONG",
            "BUTUAN CITY|OBRERO POB. (BGY. 18)",
            "BUTUAN CITY|ONG YIU POB. (BGY. 16)",
            "BUTUAN CITY|PAGATPATAN",
            "BUTUAN CITY|PANGABUGAN",
            "BUTUAN CITY|PIANING",
            "BUTUAN CITY|PIGDAULAN",
            "BUTUAN CITY|PINAMANCULAN",
            "BUTUAN CITY|PORT POYOHON POB. (BGY. 17 - NEW ASIA)",
            "BUTUAN CITY|RAJAH SOLIMAN POB. (BGY. 4)",
            "BUTUAN CITY|SALVACION",
            "BUTUAN CITY|SAN IGNACIO POB. (BGY. 15)",
            "BUTUAN CITY|SAN MATEO",
            "BUTUAN CITY|SAN VICENTE",
            "BUTUAN CITY|SANTO NIÑO",
            "BUTUAN CITY|SIKATUNA POB. (BGY. 10)",
            "BUTUAN CITY|SILONGAN POB. (BGY. 5)",
            "BUTUAN CITY|SUMILE",
            "BUTUAN CITY|SUMILIHON",
            "BUTUAN CITY|TAGABACA",
            "BUTUAN CITY|TAGUIBO",
            "BUTUAN CITY|TALIGAMAN",
            "BUTUAN CITY|TANDANG SORA POB. (BGY. 12)",
            "BUTUAN CITY|TINIWISAN",
            "BUTUAN CITY|TUNGAO",
            "BUTUAN CITY|URDUJA POB. (BGY. 9)",
            "BUTUAN CITY|VILLA KANANGA",
            "CABADBARAN CITY|ANTONIO LUNA",
            "CABADBARAN CITY|BAY-ANG",
            "CABADBARAN CITY|BAYABAS",
            "CABADBARAN CITY|CAASINAN",
            "CABADBARAN CITY|CABINET",
            "CABADBARAN CITY|CALAMBA",
            "CABADBARAN CITY|CALIBUNAN",
            "CABADBARAN CITY|COMAGASCAS",
            "CABADBARAN CITY|CONCEPCION",
            "CABADBARAN CITY|DEL PILAR",
            "CABADBARAN CITY|KATUGASAN",
            "CABADBARAN CITY|KAUSWAGAN",
            "CABADBARAN CITY|LA UNION",
            "CABADBARAN CITY|MABINI",
            "CABADBARAN CITY|MAHABA",
            "CABADBARAN CITY|POBLACION 1",
            "CABADBARAN CITY|POBLACION 2",
            "CABADBARAN CITY|POBLACION 3",
            "CABADBARAN CITY|POBLACION 4",
            "CABADBARAN CITY|POBLACION 5",
            "CABADBARAN CITY|POBLACION 6",
            "CABADBARAN CITY|POBLACION 7",
            "CABADBARAN CITY|POBLACION 8",
            "CABADBARAN CITY|POBLACION 9",
            "CABADBARAN CITY|POBLACION 10",
            "CABADBARAN CITY|POBLACION 11",
            "CABADBARAN CITY|POBLACION 12",
            "CABADBARAN CITY|PUTING BATO",
            "CABADBARAN CITY|SANGHAN",
            "CABADBARAN CITY|SORIANO",
            "CABADBARAN CITY|TOLOSA",
            "CARMEN|CAHAYAGAN",
            "CARMEN|GOSOON",
            "CARMEN|MANOLIGAO",
            "CARMEN|POBLACION (CARMEN)",
            "CARMEN|ROJALES",
            "CARMEN|SAN AGUSTIN",
            "CARMEN|TAGCATONG",
            "CARMEN|VINAPOR",
            "JABONGA|A. BELTRAN (CAMALIG)",
            "JABONGA|BALEGUIAN",
            "JABONGA|BANGONAY",
            "JABONGA|BUNGA",
            "JABONGA|COLORADO",
            "JABONGA|CUYAGO",
            "JABONGA|LIBAS",
            "JABONGA|MAGDAGOOC",
            "JABONGA|MAGSAYSAY",
            "JABONGA|MARAIGING",
            "JABONGA|POBLACION (JABONGA)",
            "JABONGA|SAN JOSE",
            "JABONGA|SAN PABLO",
            "JABONGA|SAN VICENTE",
            "JABONGA|SANTO NIÑO",
            "KITCHARAO|BANGAYAN",
            "KITCHARAO|CANAWAY",
            "KITCHARAO|CROSSING",
            "KITCHARAO|HINIMBANGAN",
            "KITCHARAO|JALIOBONG",
            "KITCHARAO|MAHAYAHAY",
            "KITCHARAO|POBLACION",
            "KITCHARAO|SAN ISIDRO",
            "KITCHARAO|SAN ROQUE",
            "KITCHARAO|SANGAY",
            "KITCHARAO|SONGKOY",
            "LAS NIEVES|AMBACON",
            "LAS NIEVES|BALUNGAGAN",
            "LAS NIEVES|BONIFACIO",
            "LAS NIEVES|CASIKLAN",
            "LAS NIEVES|CONSORCIA",
            "LAS NIEVES|DURIAN",
            "LAS NIEVES|EDUARDO G. MONTILLA (CAMBOAYON)",
            "LAS NIEVES|IBUAN",
            "LAS NIEVES|KATIPUNAN",
            "LAS NIEVES|LINGAYAO",
            "LAS NIEVES|MALICATO",
            "LAS NIEVES|MANINGALAO",
            "LAS NIEVES|MARCOS CALO",
            "LAS NIEVES|MAT-I",
            "LAS NIEVES|PINANA-AN",
            "LAS NIEVES|POBLACION",
            "LAS NIEVES|ROSARIO",
            "LAS NIEVES|SAN ISIDRO",
            "LAS NIEVES|SAN ROQUE",
            "LAS NIEVES|TINUCORAN",
            "MAGALLANES|BUHANG",
            "MAGALLANES|CALOC-AN",
            "MAGALLANES|GUIASAN",
            "MAGALLANES|MARCOS",
            "MAGALLANES|POBLACION",
            "MAGALLANES|SANTO NIÑO",
            "MAGALLANES|SANTO ROSARIO",
            "MAGALLANES|TAOD-OY",
            "NASIPIT|ACLAN",
            "NASIPIT|AMONTAY",
            "NASIPIT|ATA-ATAHON",
            "NASIPIT|BARANGAY 1 (POB.)",
            "NASIPIT|BARANGAY 2 (POB.)",
            "NASIPIT|BARANGAY 3 (POB.)",
            "NASIPIT|BARANGAY 4 (POB.)",
            "NASIPIT|BARANGAY 5 (POB.)",
            "NASIPIT|BARANGAY 6 (POB.)",
            "NASIPIT|BARANGAY 7 (POB.)",
            "NASIPIT|CAMAGONG",
            "NASIPIT|CUBI-CUBI",
            "NASIPIT|CULIT",
            "NASIPIT|JAGUIMITAN",
            "NASIPIT|KINABJANGAN",
            "NASIPIT|PUNTA",
            "NASIPIT|SANTA ANA",
            "NASIPIT|TALISAY",
            "NASIPIT|TRIANGULO",
            "REMEDIOS T. ROMUALDEZ|BALANGBALANG",
            "REMEDIOS T. ROMUALDEZ|BASILISA",
            "REMEDIOS T. ROMUALDEZ|HUMILOG",
            "REMEDIOS T. ROMUALDEZ|PANAYTAYON",
            "REMEDIOS T. ROMUALDEZ|POBLACION I (AGAY)",
            "REMEDIOS T. ROMUALDEZ|POBLACION II",
            "REMEDIOS T. ROMUALDEZ|SAN ANTONIO",
            "REMEDIOS T. ROMUALDEZ|TAGBONGABONG",
            "SANTIAGO|CURVA",
            "SANTIAGO|ESTANISLAO MORGADO",
            "SANTIAGO|JAGUPIT",
            "SANTIAGO|LA PAZ",
            "SANTIAGO|PANGAYLAN-IP",
            "SANTIAGO|POBLACION I",
            "SANTIAGO|POBLACION II",
            "SANTIAGO|SAN ISIDRO",
            "SANTIAGO|TAGBUYACAN",
            "TUBAY|BINUANGAN",
            "TUBAY|CABAYAWA",
            "TUBAY|DOÑA ROSARIO",
            "TUBAY|DOÑA TELESFORA",
            "TUBAY|LA FRATERNIDAD",
            "TUBAY|LAWIGAN",
            "TUBAY|POBLACION 1",
            "TUBAY|POBLACION 2",
            "TUBAY|SANTA ANA",
            "TUBAY|TAGMAMARKAY",
            "TUBAY|TAGPANGAHOY",
            "TUBAY|TINIGBASAN",
            "TUBAY|VICTORY",
            "BAYUGAN CITY|BERSEBA",
            "BAYUGAN CITY|BUCAC",
            "BAYUGAN CITY|CAGBAS",
            "BAYUGAN CITY|CALAITAN",
            "BAYUGAN CITY|CANAYUGAN",
            "BAYUGAN CITY|CHARITO",
            "BAYUGAN CITY|CLARO CORTEZ",
            "BAYUGAN CITY|FILI",
            "BAYUGAN CITY|GAMAO",
            "BAYUGAN CITY|GETSEMANE",
            "BAYUGAN CITY|GRACE ESTATE",
            "BAYUGAN CITY|HAMOGAWAY",
            "BAYUGAN CITY|KATIPUNAN",
            "BAYUGAN CITY|MABUHAY",
            "BAYUGAN CITY|MAGKIANGKANG",
            "BAYUGAN CITY|MAHAYAG",
            "BAYUGAN CITY|MARCELINA",
            "BAYUGAN CITY|MAYGATASAN",
            "BAYUGAN CITY|MONTIVESTA",
            "BAYUGAN CITY|MT. ARARAT",
            "BAYUGAN CITY|MT. CARMEL",
            "BAYUGAN CITY|MT. OLIVE",
            "BAYUGAN CITY|NEW SALEM",
            "BAYUGAN CITY|NOLI",
            "BAYUGAN CITY|OSMEÑA",
            "BAYUGAN CITY|PANAYTAY",
            "BAYUGAN CITY|PINAGALAAN",
            "BAYUGAN CITY|POBLACION",
            "BAYUGAN CITY|SAGMONE",
            "BAYUGAN CITY|SAGUMA",
            "BAYUGAN CITY|SALVACION",
            "BAYUGAN CITY|SAN AGUSTIN",
            "BAYUGAN CITY|SAN ISIDRO",
            "BAYUGAN CITY|SAN JUAN",
            "BAYUGAN CITY|SANTA IRENE",
            "BAYUGAN CITY|SANTA TERESITA",
            "BAYUGAN CITY|SANTO NIÑO",
            "BAYUGAN CITY|TAGLATAWAN",
            "BAYUGAN CITY|TAGLIBAS",
            "BAYUGAN CITY|TAGUBAY",
            "BAYUGAN CITY|VERDU",
            "BAYUGAN CITY|VILLA UNDAYON",
            "BAYUGAN CITY|WAWA",
            "BUNAWAN|BUNAWAN BROOK",
            "BUNAWAN|CONSUELO",
            "BUNAWAN|IMELDA",
            "BUNAWAN|LIBERTAD",
            "BUNAWAN|MAMBALILI",
            "BUNAWAN|NUEVA ERA",
            "BUNAWAN|POBLACION",
            "BUNAWAN|SAN ANDRES",
            "BUNAWAN|SAN MARCOS",
            "BUNAWAN|SAN TEODORO",
            "ESPERANZA|AGSABU",
            "ESPERANZA|AGUINALDO",
            "ESPERANZA|ANOLINGAN",
            "ESPERANZA|BAKINGKING",
            "ESPERANZA|BALUBO",
            "ESPERANZA|BENTAHON",
            "ESPERANZA|BUNAGUIT",
            "ESPERANZA|CATMONON",
            "ESPERANZA|CEBULAN",
            "ESPERANZA|CONCORDIA",
            "ESPERANZA|CROSSING LUNA",
            "ESPERANZA|CUBO",
            "ESPERANZA|DAKUTAN",
            "ESPERANZA|DUANGAN",
            "ESPERANZA|GUADALUPE",
            "ESPERANZA|GUIBONON",
            "ESPERANZA|HAWILIAN",
            "ESPERANZA|KALABUAN",
            "ESPERANZA|KINAMAYBAY",
            "ESPERANZA|LABAO",
            "ESPERANZA|LANGAG",
            "ESPERANZA|MAASIN",
            "ESPERANZA|MAC-ARTHUR",
            "ESPERANZA|MAHAGCOT",
            "ESPERANZA|MALIWANAG",
            "ESPERANZA|MILAGROS",
            "ESPERANZA|NATO",
            "ESPERANZA|NEW GINGOOG",
            "ESPERANZA|ODIONG",
            "ESPERANZA|ORO",
            "ESPERANZA|PIGLAWIGAN",
            "ESPERANZA|POBLACION",
            "ESPERANZA|REMEDIOS",
            "ESPERANZA|SALUG",
            "ESPERANZA|SAN ISIDRO",
            "ESPERANZA|SAN JOSE",
            "ESPERANZA|SAN TORIBIO",
            "ESPERANZA|SAN VICENTE",
            "ESPERANZA|SANTA FE",
            "ESPERANZA|SEGUNDA",
            "ESPERANZA|SINAKUNGAN",
            "ESPERANZA|TAGABASE",
            "ESPERANZA|TAGANAHAW",
            "ESPERANZA|TAGBALILI",
            "ESPERANZA|TAHINA",
            "ESPERANZA|TANDANG SORA",
            "ESPERANZA|VALENTINA",
            "LA PAZ|ANGELES",
            "LA PAZ|BATAAN",
            "LA PAZ|COMOTA",
            "LA PAZ|HALAPITAN",
            "LA PAZ|KASAPA II",
            "LA PAZ|LANGASIAN",
            "LA PAZ|LYDIA",
            "LA PAZ|OSMEÑA, SR.",
            "LA PAZ|PANAGANGAN",
            "LA PAZ|POBLACION",
            "LA PAZ|SABANG ADGAWAN",
            "LA PAZ|SAGUNTO",
            "LA PAZ|SAN PATRICIO",
            "LA PAZ|VALENTINA",
            "LA PAZ|VILLA PAZ",
            "LORETO|BINUCAYAN",
            "LORETO|JOHNSON",
            "LORETO|KASAPA",
            "LORETO|KATIPUNAN",
            "LORETO|KAUSWAGAN",
            "LORETO|MAGAUD",
            "LORETO|NUEVA GRACIA",
            "LORETO|POBLACION",
            "LORETO|SABUD",
            "LORETO|SAN ISIDRO",
            "LORETO|SAN MARIANO",
            "LORETO|SAN VICENTE",
            "LORETO|SANTA TERESA",
            "LORETO|SANTO NIÑO",
            "LORETO|SANTO TOMAS",
            "LORETO|VIOLANTA",
            "LORETO|WALOE",
            "PROSPERIDAD|AURORA",
            "PROSPERIDAD|AWA",
            "PROSPERIDAD|AZPETIA",
            "PROSPERIDAD|LA CARIDAD",
            "PROSPERIDAD|LA PERIAN",
            "PROSPERIDAD|LA PURISIMA",
            "PROSPERIDAD|LA SUERTE",
            "PROSPERIDAD|LA UNION",
            "PROSPERIDAD|LAS NAVAS",
            "PROSPERIDAD|LIBERTAD",
            "PROSPERIDAD|LOS ARCOS",
            "PROSPERIDAD|LUCENA",
            "PROSPERIDAD|MABUHAY",
            "PROSPERIDAD|MAGSAYSAY",
            "PROSPERIDAD|MAPAGA",
            "PROSPERIDAD|NAPO",
            "PROSPERIDAD|NEW MAUG",
            "PROSPERIDAD|PATIN-AY",
            "PROSPERIDAD|POBLACION (BAHBAH)",
            "PROSPERIDAD|SALIMBOGAON",
            "PROSPERIDAD|SALVACION",
            "PROSPERIDAD|SAN JOAQUIN",
            "PROSPERIDAD|SAN JOSE",
            "PROSPERIDAD|SAN LORENZO",
            "PROSPERIDAD|SAN MARTIN",
            "PROSPERIDAD|SAN PEDRO",
            "PROSPERIDAD|SAN RAFAEL",
            "PROSPERIDAD|SAN ROQUE",
            "PROSPERIDAD|SAN SALVADOR",
            "PROSPERIDAD|SAN VICENTE",
            "PROSPERIDAD|SANTA IRENE",
            "PROSPERIDAD|SANTA MARIA",
            "ROSARIO|BAYUGAN 3",
            "ROSARIO|CABANTAO",
            "ROSARIO|CABAWAN",
            "ROSARIO|LIBUAC",
            "ROSARIO|MALIGAYA",
            "ROSARIO|MARFIL",
            "ROSARIO|NOVELE",
            "ROSARIO|POBLACION",
            "ROSARIO|SANTA CRUZ",
            "ROSARIO|TAGBAYAGAN",
            "ROSARIO|WASI-AN",
            "SAN FRANCISCO|ALEGRIA",
            "SAN FRANCISCO|BARANGAY 1 (POB.)",
            "SAN FRANCISCO|BARANGAY 2 (POB.)",
            "SAN FRANCISCO|BARANGAY 3 (POB.)",
            "SAN FRANCISCO|BARANGAY 4 (POB.)",
            "SAN FRANCISCO|BARANGAY 5 (POB.)",
            "SAN FRANCISCO|BAYUGAN 2",
            "SAN FRANCISCO|BITAN-AGAN",
            "SAN FRANCISCO|BORBON",
            "SAN FRANCISCO|BUENASUERTE",
            "SAN FRANCISCO|CAIMPUGAN",
            "SAN FRANCISCO|DAS-AGAN",
            "SAN FRANCISCO|EBRO",
            "SAN FRANCISCO|HUBANG",
            "SAN FRANCISCO|KARAUS",
            "SAN FRANCISCO|LADGADAN",
            "SAN FRANCISCO|LAPINIGAN",
            "SAN FRANCISCO|LUCAC",
            "SAN FRANCISCO|MATE",
            "SAN FRANCISCO|NEW VISAYAS",
            "SAN FRANCISCO|ORMACA",
            "SAN FRANCISCO|PASTA",
            "SAN FRANCISCO|PISA-AN",
            "SAN FRANCISCO|RIZAL",
            "SAN FRANCISCO|SAN ISIDRO",
            "SAN FRANCISCO|SANTA ANA",
            "SAN FRANCISCO|TAGAPUA",
            "SAN LUIS|ANISLAGAN",
            "SAN LUIS|BALIT",
            "SAN LUIS|BAYLO",
            "SAN LUIS|BINICALAN",
            "SAN LUIS|CECILIA",
            "SAN LUIS|COALICION",
            "SAN LUIS|CULI",
            "SAN LUIS|DIMASALANG",
            "SAN LUIS|DON ALEJANDRO",
            "SAN LUIS|DON PEDRO",
            "SAN LUIS|DOÑA FLAVIA",
            "SAN LUIS|DOÑA MAXIMA",
            "SAN LUIS|MAHAGSAY",
            "SAN LUIS|MAHAPAG",
            "SAN LUIS|MAHAYAHAY",
            "SAN LUIS|MURITULA",
            "SAN LUIS|NUEVO TRABAJO",
            "SAN LUIS|POBLACION",
            "SAN LUIS|POLICARPO",
            "SAN LUIS|SAN ISIDRO",
            "SAN LUIS|SAN PEDRO",
            "SAN LUIS|SANTA INES",
            "SAN LUIS|SANTA RITA",
            "SAN LUIS|SANTIAGO",
            "SAN LUIS|WEGGUAM",
            "SANTA JOSEFA|ANGAS",
            "SANTA JOSEFA|AURORA",
            "SANTA JOSEFA|AWAO",
            "SANTA JOSEFA|CONCEPCION",
            "SANTA JOSEFA|PAG-ASA",
            "SANTA JOSEFA|PATROCINIO",
            "SANTA JOSEFA|POBLACION",
            "SANTA JOSEFA|SAN JOSE",
            "SANTA JOSEFA|SANTA ISABEL",
            "SANTA JOSEFA|SAYON",
            "SANTA JOSEFA|TAPAZ",
            "SIBAGAT|AFGA",
            "SIBAGAT|ANAHAWAN",
            "SIBAGAT|BANAGBANAG",
            "SIBAGAT|DEL ROSARIO",
            "SIBAGAT|EL RIO",
            "SIBAGAT|ILIHAN",
            "SIBAGAT|KAUSWAGAN",
            "SIBAGAT|KIOYA",
            "SIBAGAT|KOLAMBUGAN",
            "SIBAGAT|MAGKALAPE",
            "SIBAGAT|MAGSAYSAY",
            "SIBAGAT|MAHAYAHAY",
            "SIBAGAT|NEW TUBIGON",
            "SIBAGAT|PADIAY",
            "SIBAGAT|PEREZ",
            "SIBAGAT|POBLACION",
            "SIBAGAT|SAN ISIDRO",
            "SIBAGAT|SAN VICENTE",
            "SIBAGAT|SANTA CRUZ",
            "SIBAGAT|SANTA MARIA",
            "SIBAGAT|SINAI",
            "SIBAGAT|TABON-TABON",
            "SIBAGAT|TAG-UYANGO",
            "SIBAGAT|VILLANGIT",
            "TALACOGON|BATUCAN",
            "TALACOGON|BUENAGRACIA",
            "TALACOGON|CAUSWAGAN",
            "TALACOGON|CULI",
            "TALACOGON|DEL MONTE",
            "TALACOGON|DESAMPARADOS",
            "TALACOGON|LA FLORA",
            "TALACOGON|LABNIG",
            "TALACOGON|MAHARLIKA",
            "TALACOGON|MARBON",
            "TALACOGON|SABANG GIBUNG",
            "TALACOGON|SAN AGUSTIN (POB.)",
            "TALACOGON|SAN ISIDRO (POB.)",
            "TALACOGON|SAN NICOLAS (POB.)",
            "TALACOGON|ZAMORA",
            "TALACOGON|ZILLOVIA",
            "TRENTO|BASA",
            "TRENTO|CEBOLIN",
            "TRENTO|CUEVAS",
            "TRENTO|KAPATUNGAN",
            "TRENTO|LANGKILA-AN",
            "TRENTO|MANAT",
            "TRENTO|NEW VISAYAS",
            "TRENTO|PANGYAN",
            "TRENTO|POBLACION",
            "TRENTO|PULANG-LUPA",
            "TRENTO|SALVACION",
            "TRENTO|SAN IGNACIO",
            "TRENTO|SAN ISIDRO",
            "TRENTO|SAN ROQUE",
            "TRENTO|SANTA MARIA",
            "TRENTO|TUDELA",
            "VERUELA|ANITAP",
            "VERUELA|BACAY II",
            "VERUELA|BINONGAN",
            "VERUELA|CAIGANGAN",
            "VERUELA|CANDIIS",
            "VERUELA|DEL MONTE",
            "VERUELA|DON MATEO",
            "VERUELA|KATIPUNAN",
            "VERUELA|LA FORTUNA",
            "VERUELA|LIMOT",
            "VERUELA|MAGSAYSAY",
            "VERUELA|MASAYAN",
            "VERUELA|POBLACION",
            "VERUELA|SAMPAGUITA",
            "VERUELA|SAN GABRIEL",
            "VERUELA|SANTA CRUZ",
            "VERUELA|SANTA EMELIA",
            "VERUELA|SAWAGAN",
            "VERUELA|SINOBONG",
            "VERUELA|SISIMON",
            "BASILISA (RIZAL)|BENGLEN",
            "BASILISA (RIZAL)|CATADMAN",
            "BASILISA (RIZAL)|COLUMBUS",
            "BASILISA (RIZAL)|CORING",
            "BASILISA (RIZAL)|CORTES",
            "BASILISA (RIZAL)|DIEGAS",
            "BASILISA (RIZAL)|DOÑA HELENE",
            "BASILISA (RIZAL)|EDERA",
            "BASILISA (RIZAL)|FERDINAND",
            "BASILISA (RIZAL)|GEOTINA",
            "BASILISA (RIZAL)|IMEE (BACTASAN)",
            "BASILISA (RIZAL)|MELGAR",
            "BASILISA (RIZAL)|MONTAG",
            "BASILISA (RIZAL)|NAVARRO",
            "BASILISA (RIZAL)|NEW NAZARETH",
            "BASILISA (RIZAL)|POBLACION",
            "BASILISA (RIZAL)|PUERTO PRINCESA",
            "BASILISA (RIZAL)|RITA GLENDA",
            "BASILISA (RIZAL)|ROMA",
            "BASILISA (RIZAL)|ROXAS",
            "BASILISA (RIZAL)|SANTA MONICA",
            "BASILISA (RIZAL)|SANTO NIÑO",
            "BASILISA (RIZAL)|SERING",
            "BASILISA (RIZAL)|SOMBRADO",
            "BASILISA (RIZAL)|TAG-ABACA",
            "BASILISA (RIZAL)|VILLA ECLEO",
            "BASILISA (RIZAL)|VILLA PANTINOPLE",
            "CAGDIANAO|BOA",
            "CAGDIANAO|CABUNGA-AN",
            "CAGDIANAO|DEL PILAR",
            "CAGDIANAO|LAGUNA",
            "CAGDIANAO|LEGASPI",
            "CAGDIANAO|MA-ATAS",
            "CAGDIANAO|MABINI (BORJA)",
            "CAGDIANAO|NUEVA ESTRELLA",
            "CAGDIANAO|POBLACION",
            "CAGDIANAO|R. ECLEO, SR.",
            "CAGDIANAO|SAN JOSE",
            "CAGDIANAO|SANTA RITA",
            "CAGDIANAO|TIGBAO",
            "CAGDIANAO|VALENCIA",
            "DINAGAT|BAGUMBAYAN",
            "DINAGAT|CAB-ILAN",
            "DINAGAT|CABAYAWAN",
            "DINAGAT|CAYETANO",
            "DINAGAT|ESCOLTA (POB.)",
            "DINAGAT|GOMEZ",
            "DINAGAT|JUSTINIANA EDERA",
            "DINAGAT|MAGSAYSAY",
            "DINAGAT|MAUSWAGON (POB.)",
            "DINAGAT|NEW MABUHAY",
            "DINAGAT|WADAS",
            "DINAGAT|WHITE BEACH (POB.)",
            "LIBJO (ALBOR)|ALBOR (POB.)",
            "LIBJO (ALBOR)|ARELLANO",
            "LIBJO (ALBOR)|BAYANIHAN",
            "LIBJO (ALBOR)|DOÑA HELEN",
            "LIBJO (ALBOR)|GARCIA",
            "LIBJO (ALBOR)|GENERAL AGUINALDO (BOLOD-BOLOD)",
            "LIBJO (ALBOR)|KANIHAAN",
            "LIBJO (ALBOR)|LLAMERA",
            "LIBJO (ALBOR)|MAGSAYSAY",
            "LIBJO (ALBOR)|OSMEÑA",
            "LIBJO (ALBOR)|PLARIDEL",
            "LIBJO (ALBOR)|QUEZON",
            "LIBJO (ALBOR)|ROSITA",
            "LIBJO (ALBOR)|SAN ANTONIO (POB.)",
            "LIBJO (ALBOR)|SAN JOSE",
            "LIBJO (ALBOR)|SANTO NIÑO",
            "LORETO|CARMEN (POB.)",
            "LORETO|ESPERANZA",
            "LORETO|FERDINAND",
            "LORETO|HELENE",
            "LORETO|LIBERTY",
            "LORETO|MAGSAYSAY",
            "LORETO|PANAMAON",
            "LORETO|SAN JUAN (POB.)",
            "LORETO|SANTA CRUZ (POB.)",
            "LORETO|SANTIAGO (POB.)",
            "SAN JOSE|AURELIO",
            "SAN JOSE|CUARINTA",
            "SAN JOSE|DON RUBEN ECLEO (BALTAZAR)",
            "SAN JOSE|JACQUEZ",
            "SAN JOSE|JUSTINIANA EDERA",
            "SAN JOSE|LUNA",
            "SAN JOSE|MAHAYAHAY",
            "SAN JOSE|MATINGBE",
            "SAN JOSE|SAN JOSE (POB.)",
            "SAN JOSE|SAN JUAN",
            "SAN JOSE|SANTA CRUZ",
            "SAN JOSE|WILSON",
            "TUBAJON|DIAZ (ROMUALDEZ)",
            "TUBAJON|IMELDA",
            "TUBAJON|MABINI",
            "TUBAJON|MALINAO",
            "TUBAJON|NAVARRO",
            "TUBAJON|ROXAS",
            "TUBAJON|SAN ROQUE (POB.)",
            "TUBAJON|SAN VICENTE (POB.)",
            "TUBAJON|SANTA CRUZ (POB.)",
            "ALEGRIA|ALIPAO",
            "ALEGRIA|ANAHAW",
            "ALEGRIA|BUDLINGIN",
            "ALEGRIA|CAMP EDUARD (GEOTINA)",
            "ALEGRIA|FERLDA",
            "ALEGRIA|GAMUTON",
            "ALEGRIA|JULIO OUANO (POB.)",
            "ALEGRIA|OMBONG",
            "ALEGRIA|POBLACION (ALEGRIA)",
            "ALEGRIA|PONGTUD",
            "ALEGRIA|SAN JUAN",
            "ALEGRIA|SAN PEDRO",
            "BACUAG|CABUGAO",
            "BACUAG|CAMBUAYON",
            "BACUAG|CAMPO",
            "BACUAG|DUGSANGON",
            "BACUAG|PAUTAO",
            "BACUAG|PAYAPAG",
            "BACUAG|POBLACION",
            "BACUAG|PUNGTOD",
            "BACUAG|SANTO ROSARIO",
            "BURGOS|BAYBAY",
            "BURGOS|BITAUG",
            "BURGOS|MATIN-AO",
            "BURGOS|POBLACION 1",
            "BURGOS|POBLACION 2",
            "BURGOS|SAN MATEO",
            "CLAVER|BAGAKAY (POB. WEST)",
            "CLAVER|CABUGO",
            "CLAVER|CAGDIANAO",
            "CLAVER|DAYWAN",
            "CLAVER|HAYANGGABON",
            "CLAVER|LADGARON (POB.)",
            "CLAVER|LAPINIGAN",
            "CLAVER|MAGALLANES",
            "CLAVER|PANATAO",
            "CLAVER|SAPA",
            "CLAVER|TAGANITO",
            "CLAVER|TAYAGA (POB. EAST)",
            "CLAVER|URBIZTONDO",
            "CLAVER|WANGKE",
            "DAPA|BAGAKAY",
            "DAPA|BARANGAY 1 (POB.)",
            "DAPA|BARANGAY 2 (POB.)",
            "DAPA|BARANGAY 3 (POB.)",
            "DAPA|BARANGAY 4 (POB.)",
            "DAPA|BARANGAY 5 (POB.)",
            "DAPA|BARANGAY 6 (POB.)",
            "DAPA|BARANGAY 7 (POB.)",
            "DAPA|BARANGAY 8 (POB.)",
            "DAPA|BARANGAY 9 (POB.)",
            "DAPA|BARANGAY 10 (POB.)",
            "DAPA|BARANGAY 11 (POB.)",
            "DAPA|BARANGAY 12 (POB.)",
            "DAPA|BARANGAY 13 (POB.)",
            "DAPA|BUENAVISTA",
            "DAPA|CABAWA",
            "DAPA|CAMBAS-AC",
            "DAPA|CONSOLACION",
            "DAPA|CORREGIDOR",
            "DAPA|DAGOHOY",
            "DAPA|DON PAULINO",
            "DAPA|JUBANG",
            "DAPA|MONTSERRAT",
            "DAPA|OSMEÑA",
            "DAPA|SAN CARLOS",
            "DAPA|SAN MIGUEL",
            "DAPA|SANTA FE",
            "DAPA|SANTA FELOMINA",
            "DAPA|UNION",
            "DEL CARMEN|ANTIPOLO",
            "DEL CARMEN|BAGAKAY (ALBURO)",
            "DEL CARMEN|BITOON",
            "DEL CARMEN|CABUGAO",
            "DEL CARMEN|CANCOHOY",
            "DEL CARMEN|CAUB",
            "DEL CARMEN|DEL CARMEN (POB.)",
            "DEL CARMEN|DOMOYOG",
            "DEL CARMEN|ESPERANZA",
            "DEL CARMEN|HALIAN",
            "DEL CARMEN|JAMOYAON",
            "DEL CARMEN|KATIPUNAN",
            "DEL CARMEN|LOBOGON",
            "DEL CARMEN|MABUHAY",
            "DEL CARMEN|MAHAYAHAY",
            "DEL CARMEN|QUEZON",
            "DEL CARMEN|SAN FERNANDO",
            "DEL CARMEN|SAN JOSE (POB.)",
            "DEL CARMEN|SAYAK",
            "DEL CARMEN|TUBORAN",
            "GENERAL LUNA|ANAJAWAN",
            "GENERAL LUNA|CABITOONAN",
            "GENERAL LUNA|CATANGNAN",
            "GENERAL LUNA|CONSUELO",
            "GENERAL LUNA|CORAZON",
            "GENERAL LUNA|DAKU",
            "GENERAL LUNA|LA JANUZA",
            "GENERAL LUNA|LIBERTAD",
            "GENERAL LUNA|MAGSAYSAY",
            "GENERAL LUNA|MALINAO",
            "GENERAL LUNA|POBLACION I (PUROK I)",
            "GENERAL LUNA|POBLACION II (PUROK II)",
            "GENERAL LUNA|POBLACION III (PUROK III)",
            "GENERAL LUNA|POBLACION IV (PUROK IV)",
            "GENERAL LUNA|POBLACION V (PUROK V)",
            "GENERAL LUNA|SANTA CRUZ",
            "GENERAL LUNA|SANTA FE",
            "GENERAL LUNA|SUYANGAN",
            "GENERAL LUNA|TAWIN-TAWIN",
            "GIGAQUIT|ALAMBIQUE (POB.)",
            "GIGAQUIT|ANIBONGAN",
            "GIGAQUIT|CAM-BOAYON",
            "GIGAQUIT|CAMAM-ONAN",
            "GIGAQUIT|IPIL (POB.)",
            "GIGAQUIT|LAHI",
            "GIGAQUIT|MAHANUB",
            "GIGAQUIT|PONIENTE",
            "GIGAQUIT|SAN ANTONIO (BONOT)",
            "GIGAQUIT|SAN ISIDRO",
            "GIGAQUIT|SICO-SICO",
            "GIGAQUIT|VILLAFLOR",
            "GIGAQUIT|VILLAFRANCA",
            "MAINIT|BINGA",
            "MAINIT|BOBONA-ON",
            "MAINIT|CANTUGAS",
            "MAINIT|DAYANO",
            "MAINIT|MABINI",
            "MAINIT|MAGPAYANG",
            "MAINIT|MAGSAYSAY (POB.)",
            "MAINIT|MANSAYAO",
            "MAINIT|MARAYAG",
            "MAINIT|MATIN-AO",
            "MAINIT|PACO",
            "MAINIT|QUEZON (POB.)",
            "MAINIT|ROXAS",
            "MAINIT|SAN FRANCISCO",
            "MAINIT|SAN ISIDRO",
            "MAINIT|SAN JOSE",
            "MAINIT|SIANA",
            "MAINIT|SILOP",
            "MAINIT|TAGBUYAWAN",
            "MAINIT|TAPI-AN",
            "MAINIT|TOLINGON",
            "MALIMONO|BUNYASAN",
            "MALIMONO|CAGTINAE",
            "MALIMONO|CAN-AGA",
            "MALIMONO|CANSAYONG",
            "MALIMONO|CANTAPOY",
            "MALIMONO|CAYAWAN",
            "MALIMONO|DORO (BINOCARAN)",
            "MALIMONO|HANAGDONG",
            "MALIMONO|KARIHATAG",
            "MALIMONO|MASGAD",
            "MALIMONO|PILI",
            "MALIMONO|SAN ISIDRO (POB.)",
            "MALIMONO|TINAGO",
            "MALIMONO|VILLARIZA",
            "PILAR|ASINAN (POB.)",
            "PILAR|CARIDAD",
            "PILAR|CENTRO (POB.)",
            "PILAR|CONSOLACION",
            "PILAR|DATU",
            "PILAR|DAYAOHAY",
            "PILAR|JABOY",
            "PILAR|KATIPUNAN",
            "PILAR|MAASIN",
            "PILAR|MABINI",
            "PILAR|MABUHAY",
            "PILAR|PILARING (POB.)",
            "PILAR|PUNTA (POB.)",
            "PILAR|SALVACION",
            "PILAR|SAN ROQUE",
            "PLACER|AMOSLOG",
            "PLACER|ANISLAGAN",
            "PLACER|BAD-AS",
            "PLACER|BOYONGAN",
            "PLACER|BUGAS-BUGAS",
            "PLACER|CENTRAL (POB.)",
            "PLACER|ELLAPERAL (NONOK)",
            "PLACER|IPIL (POB.)",
            "PLACER|LAKANDULA",
            "PLACER|MABINI",
            "PLACER|MACALAYA",
            "PLACER|MAGSAYSAY (POB.)",
            "PLACER|MAGUPANGE",
            "PLACER|PANANAY-AN",
            "PLACER|PANHUTONGAN",
            "PLACER|SAN ISIDRO",
            "PLACER|SANI-SANI",
            "PLACER|SANTA CRUZ",
            "PLACER|SUYOC",
            "PLACER|TAGBONGABONG",
            "SAN BENITO|BONGDO",
            "SAN BENITO|MARIBOJOC",
            "SAN BENITO|NUEVO CAMPO",
            "SAN BENITO|SAN JUAN",
            "SAN BENITO|SANTA CRUZ (POB.)",
            "SAN BENITO|TALISAY (POB.)",
            "SAN FRANCISCO (ANAO-AON)|AMONTAY",
            "SAN FRANCISCO (ANAO-AON)|BALITE",
            "SAN FRANCISCO (ANAO-AON)|BANBANON",
            "SAN FRANCISCO (ANAO-AON)|DIAZ",
            "SAN FRANCISCO (ANAO-AON)|HONRADO",
            "SAN FRANCISCO (ANAO-AON)|JUBGAN",
            "SAN FRANCISCO (ANAO-AON)|LINONGGANAN",
            "SAN FRANCISCO (ANAO-AON)|MACOPA",
            "SAN FRANCISCO (ANAO-AON)|MAGTANGALE",
            "SAN FRANCISCO (ANAO-AON)|OSLAO",
            "SAN FRANCISCO (ANAO-AON)|POBLACION",
            "SAN ISIDRO|BUHING CALIPAY",
            "SAN ISIDRO|DEL CARMEN (POB.)",
            "SAN ISIDRO|DEL PILAR",
            "SAN ISIDRO|MACAPAGAL",
            "SAN ISIDRO|PACIFICO",
            "SAN ISIDRO|PELAEZ",
            "SAN ISIDRO|ROXAS",
            "SAN ISIDRO|SAN MIGUEL",
            "SAN ISIDRO|SANTA PAZ",
            "SAN ISIDRO|SANTO NIÑO",
            "SAN ISIDRO|TAMBACAN",
            "SAN ISIDRO|TIGASAO",
            "SANTA MONICA (SAPAO)|ABAD SANTOS",
            "SANTA MONICA (SAPAO)|ALEGRIA",
            "SANTA MONICA (SAPAO)|BAILAN",
            "SANTA MONICA (SAPAO)|GARCIA",
            "SANTA MONICA (SAPAO)|LIBERTAD",
            "SANTA MONICA (SAPAO)|MABINI",
            "SANTA MONICA (SAPAO)|MABUHAY (POB.)",
            "SANTA MONICA (SAPAO)|MAGSAYSAY",
            "SANTA MONICA (SAPAO)|RIZAL",
            "SANTA MONICA (SAPAO)|T. ARLAN (POB.)",
            "SANTA MONICA (SAPAO)|TANGBO",
            "SISON|BIYABID",
            "SISON|GACEPAN",
            "SISON|IMA",
            "SISON|LOWER PATAG",
            "SISON|MABUHAY",
            "SISON|MAYAG",
            "SISON|POBLACION (SAN PEDRO)",
            "SISON|SAN ISIDRO",
            "SISON|SAN PABLO",
            "SISON|TAGBAYANI",
            "SISON|TINOGPAHAN",
            "SISON|UPPER PATAG",
            "SOCORRO|ALBINO TARUC",
            "SOCORRO|DEL PILAR",
            "SOCORRO|HELENE",
            "SOCORRO|HONRADO",
            "SOCORRO|NAVARRO (POB.)",
            "SOCORRO|NUEVA ESTRELLA",
            "SOCORRO|PAMOSAINGAN",
            "SOCORRO|RIZAL (POB.)",
            "SOCORRO|SALOG",
            "SOCORRO|SAN ROQUE",
            "SOCORRO|SANTA CRUZ",
            "SOCORRO|SERING",
            "SOCORRO|SONGKOY",
            "SOCORRO|SUDLON",
            "SURIGAO CITY|ALANG-ALANG",
            "SURIGAO CITY|ALEGRIA",
            "SURIGAO CITY|ANOMAR",
            "SURIGAO CITY|AURORA",
            "SURIGAO CITY|BALIBAYON",
            "SURIGAO CITY|BAYBAY",
            "SURIGAO CITY|BILABID",
            "SURIGAO CITY|BITAUGAN",
            "SURIGAO CITY|BONIFACIO",
            "SURIGAO CITY|BUENAVISTA",
            "SURIGAO CITY|CABONGBONGAN",
            "SURIGAO CITY|CAGNIOG",
            "SURIGAO CITY|CAGUTSAN",
            "SURIGAO CITY|CANLANIPA",
            "SURIGAO CITY|CANTIASAY",
            "SURIGAO CITY|CAPALAYAN",
            "SURIGAO CITY|CATADMAN",
            "SURIGAO CITY|DANAO",
            "SURIGAO CITY|DANAWAN",
            "SURIGAO CITY|DAY-ASAN",
            "SURIGAO CITY|IPIL",
            "SURIGAO CITY|LIBUAC",
            "SURIGAO CITY|LIPATA",
            "SURIGAO CITY|LISONDRA",
            "SURIGAO CITY|LUNA",
            "SURIGAO CITY|MABINI",
            "SURIGAO CITY|MABUA",
            "SURIGAO CITY|MANYAGAO",
            "SURIGAO CITY|MAPAWA",
            "SURIGAO CITY|MAT-I",
            "SURIGAO CITY|NABAGO",
            "SURIGAO CITY|NONOC",
            "SURIGAO CITY|OROK",
            "SURIGAO CITY|POCTOY",
            "SURIGAO CITY|PUNTA BILAR",
            "SURIGAO CITY|QUEZON",
            "SURIGAO CITY|RIZAL",
            "SURIGAO CITY|SABANG",
            "SURIGAO CITY|SAN ISIDRO",
            "SURIGAO CITY|SAN JOSE",
            "SURIGAO CITY|SAN JUAN",
            "SURIGAO CITY|SAN PEDRO (HANIGAD)",
            "SURIGAO CITY|SAN ROQUE",
            "SURIGAO CITY|SERNA (BAD-ASAY)",
            "SURIGAO CITY|SIDLAKAN",
            "SURIGAO CITY|SILOP",
            "SURIGAO CITY|SUGBAY",
            "SURIGAO CITY|SUKAILANG",
            "SURIGAO CITY|TAFT (POB.)",
            "SURIGAO CITY|TALISAY",
            "SURIGAO CITY|TOGBONGON",
            "SURIGAO CITY|TRINIDAD",
            "SURIGAO CITY|WASHINGTON (POB.)",
            "SURIGAO CITY|ZARAGOZA",
            "TAGANA-AN|AURORA (POB.)",
            "TAGANA-AN|AZUCENA (POB.)",
            "TAGANA-AN|BANBAN",
            "TAGANA-AN|CAWILAN",
            "TAGANA-AN|FABIO",
            "TAGANA-AN|HIMAMAUG",
            "TAGANA-AN|LAUREL",
            "TAGANA-AN|LOWER LIBAS",
            "TAGANA-AN|OPONG",
            "TAGANA-AN|PATINO",
            "TAGANA-AN|SAMPAGUITA (POB.)",
            "TAGANA-AN|TALAVERA",
            "TAGANA-AN|UNION",
            "TAGANA-AN|UPPER LIBAS",
            "TUBOD|CAPAYAHAN",
            "TUBOD|CAWILAN",
            "TUBOD|DEL ROSARIO",
            "TUBOD|MARGA",
            "TUBOD|MOTORPOOL",
            "TUBOD|POBLACION (TUBOD)",
            "TUBOD|SAN ISIDRO",
            "TUBOD|SAN PABLO",
            "TUBOD|TIMAMANA",
            "BAROBO|AMAGA",
            "BAROBO|BAHI",
            "BAROBO|CABACUNGAN",
            "BAROBO|CAMBAGANG",
            "BAROBO|CAUSWAGAN",
            "BAROBO|DAPDAP",
            "BAROBO|DUGHAN",
            "BAROBO|GAMUT",
            "BAROBO|JAVIER",
            "BAROBO|KINAYAN",
            "BAROBO|MAMIS",
            "BAROBO|POBLACION",
            "BAROBO|RIZAL",
            "BAROBO|SAN JOSE",
            "BAROBO|SAN ROQUE",
            "BAROBO|SAN VICENTE",
            "BAROBO|SUA",
            "BAROBO|SUDLON",
            "BAROBO|TAMBIS",
            "BAROBO|UNIDAD",
            "BAROBO|WAKAT",
            "BAYABAS|AMAG",
            "BAYABAS|BALETE (POB.)",
            "BAYABAS|CABUGO",
            "BAYABAS|CAGBAOTO",
            "BAYABAS|LA PAZ",
            "BAYABAS|MAGOBAWOK",
            "BAYABAS|PANAOSAWON",
            "BISLIG CITY|BUCTO",
            "BISLIG CITY|BURBOANAN",
            "BISLIG CITY|CAGUYAO",
            "BISLIG CITY|COLETO",
            "BISLIG CITY|COMAWAS",
            "BISLIG CITY|KAHAYAG",
            "BISLIG CITY|LABISMA",
            "BISLIG CITY|LAWIGAN",
            "BISLIG CITY|MAHARLIKA",
            "BISLIG CITY|MANGAGOY",
            "BISLIG CITY|MONE",
            "BISLIG CITY|PAMANLINAN",
            "BISLIG CITY|PAMAYPAYAN",
            "BISLIG CITY|POBLACION",
            "BISLIG CITY|SAN ANTONIO",
            "BISLIG CITY|SAN FERNANDO",
            "BISLIG CITY|SAN ISIDRO (BAGNAN)",
            "BISLIG CITY|SAN JOSE",
            "BISLIG CITY|SAN ROQUE (CADANGLASAN)",
            "BISLIG CITY|SAN VICENTE",
            "BISLIG CITY|SANTA CRUZ",
            "BISLIG CITY|SIBAROY",
            "BISLIG CITY|TABON",
            "BISLIG CITY|TUMANAN",
            "CAGWAIT|ARAS-ASAN",
            "CAGWAIT|BACOLOD",
            "CAGWAIT|BITAUGAN EAST",
            "CAGWAIT|BITAUGAN WEST",
            "CAGWAIT|LA PURISIMA (PALHE)",
            "CAGWAIT|LACTUDAN",
            "CAGWAIT|MAT-E",
            "CAGWAIT|POBLACION",
            "CAGWAIT|TAWAGAN",
            "CAGWAIT|TUBO-TUBO",
            "CAGWAIT|UNIDAD",
            "CANTILAN|BUGSUKAN",
            "CANTILAN|BUNTALID",
            "CANTILAN|CABANGAHAN",
            "CANTILAN|CABAS-AN",
            "CANTILAN|CALAGDAAN",
            "CANTILAN|CONSUELO",
            "CANTILAN|GENERAL ISLAND",
            "CANTILAN|LININTI-AN (POB.)",
            "CANTILAN|LOBO",
            "CANTILAN|MAGASANG",
            "CANTILAN|MAGOSILOM (POB.)",
            "CANTILAN|PAG-ANTAYAN",
            "CANTILAN|PALASAO",
            "CANTILAN|PARANG",
            "CANTILAN|SAN PEDRO",
            "CANTILAN|TAPI",
            "CANTILAN|TIGABONG",
            "CARMEN|ANTAO",
            "CARMEN|CANCAVAN",
            "CARMEN|CARMEN (POB.)",
            "CARMEN|ESPERANZA",
            "CARMEN|HINAPOYAN",
            "CARMEN|PUYAT",
            "CARMEN|SAN VICENTE",
            "CARMEN|SANTA CRUZ",
            "CARRASCAL|ADLAY",
            "CARRASCAL|BABUYAN",
            "CARRASCAL|BACOLOD",
            "CARRASCAL|BAYBAY (POB.)",
            "CARRASCAL|BON-OT",
            "CARRASCAL|CAGLAYAG",
            "CARRASCAL|DAHICAN",
            "CARRASCAL|DOYOS (POB.)",
            "CARRASCAL|EMBARCADERO (POB.)",
            "CARRASCAL|GAMUTON",
            "CARRASCAL|PANIKIAN",
            "CARRASCAL|PANTUKAN",
            "CARRASCAL|SACA (POB.)",
            "CARRASCAL|TAG-ANITO",
            "CORTES|BALIBADON",
            "CORTES|BURGOS",
            "CORTES|CAPANDAN",
            "CORTES|MABAHIN",
            "CORTES|MADRELINO",
            "CORTES|MANLICO",
            "CORTES|MATHO",
            "CORTES|POBLACION",
            "CORTES|TAG-ANONGAN",
            "CORTES|TIGAO",
            "CORTES|TUBORAN",
            "CORTES|UBA",
            "HINATUAN|BACULIN",
            "HINATUAN|BENIGNO AQUINO (ZONE I) POB.",
            "HINATUAN|BIGAAN",
            "HINATUAN|CAMBATONG",
            "HINATUAN|CAMPA",
            "HINATUAN|DUGMANON",
            "HINATUAN|HARIP",
            "HINATUAN|LA CASA (POB.)",
            "HINATUAN|LOYOLA",
            "HINATUAN|MALIGAYA",
            "HINATUAN|PAGTIGNI-AN (BITOON)",
            "HINATUAN|POCTO",
            "HINATUAN|PORT LAMON",
            "HINATUAN|ROXAS",
            "HINATUAN|SAN JUAN",
            "HINATUAN|SASA",
            "HINATUAN|TAGASAKA",
            "HINATUAN|TAGBOBONGA",
            "HINATUAN|TALISAY",
            "HINATUAN|TARUSAN",
            "HINATUAN|TIDMAN",
            "HINATUAN|TIWI",
            "HINATUAN|ZONE II (POB.)",
            "HINATUAN|ZONE III MAHARLIKA (POB.)",
            "LANUZA|AGSAM",
            "LANUZA|BOCAWE",
            "LANUZA|BUNGA",
            "LANUZA|GAMUTON",
            "LANUZA|HABAG",
            "LANUZA|MAMPI",
            "LANUZA|NURCIA",
            "LANUZA|PAKWAN",
            "LANUZA|SIBAHAY",
            "LANUZA|ZONE I (POB.)",
            "LANUZA|ZONE II (POB.)",
            "LANUZA|ZONE III (POB.)",
            "LANUZA|ZONE IV (POB.)",
            "LIANGA|ANIBONGAN",
            "LIANGA|BAN-AS",
            "LIANGA|BANAHAO",
            "LIANGA|BAUCAWE",
            "LIANGA|DIATAGON",
            "LIANGA|GANAYON",
            "LIANGA|LIATIMCO",
            "LIANGA|MANYAYAY",
            "LIANGA|PAYASAN",
            "LIANGA|POBLACION",
            "LIANGA|SAINT CHRISTINE",
            "LIANGA|SAN ISIDRO",
            "LIANGA|SAN PEDRO",
            "LINGIG|ANIBONGAN",
            "LINGIG|BARCELONA",
            "LINGIG|BOGAK",
            "LINGIG|BONGAN",
            "LINGIG|HANDAMAYAN",
            "LINGIG|MAHAYAHAY",
            "LINGIG|MANDUS",
            "LINGIG|MANSA-ILAO",
            "LINGIG|PAGTILA-AN",
            "LINGIG|PALO ALTO",
            "LINGIG|POBLACION",
            "LINGIG|RAJAH CABUNGSO-AN",
            "LINGIG|SABANG",
            "LINGIG|SALVACION",
            "LINGIG|SAN ROQUE",
            "LINGIG|TAGPOPORAN",
            "LINGIG|UNION",
            "LINGIG|VALENCIA",
            "MADRID|BAGSAC",
            "MADRID|BAYOGO",
            "MADRID|LINIBONAN",
            "MADRID|MAGSAYSAY",
            "MADRID|MANGA",
            "MADRID|PANAYOGON",
            "MADRID|PATONG PATONG",
            "MADRID|QUIRINO (POB.)",
            "MADRID|SAN ANTONIO",
            "MADRID|SAN JUAN",
            "MADRID|SAN ROQUE",
            "MADRID|SAN VICENTE",
            "MADRID|SONGKIT",
            "MADRID|UNION",
            "MARIHATAG|ALEGRIA",
            "MARIHATAG|AMONTAY",
            "MARIHATAG|ANTIPOLO",
            "MARIHATAG|AROROGAN",
            "MARIHATAG|BAYAN",
            "MARIHATAG|MAHABA",
            "MARIHATAG|MARARAG",
            "MARIHATAG|POBLACION",
            "MARIHATAG|SAN ANTONIO",
            "MARIHATAG|SAN ISIDRO",
            "MARIHATAG|SAN PEDRO",
            "MARIHATAG|SANTA CRUZ",
            "SAN AGUSTIN|BRETANIA",
            "SAN AGUSTIN|BUATONG",
            "SAN AGUSTIN|BUHISAN",
            "SAN AGUSTIN|GATA",
            "SAN AGUSTIN|HORNASAN",
            "SAN AGUSTIN|JANIPAAN",
            "SAN AGUSTIN|KAUSWAGAN",
            "SAN AGUSTIN|OTEIZA",
            "SAN AGUSTIN|POBLACION",
            "SAN AGUSTIN|PONG-ON",
            "SAN AGUSTIN|PONGTOD",
            "SAN AGUSTIN|SALVACION",
            "SAN AGUSTIN|SANTO NIÑO",
            "SAN MIGUEL|BAGYANG",
            "SAN MIGUEL|BARAS",
            "SAN MIGUEL|BITAUGAN",
            "SAN MIGUEL|BOLHOON",
            "SAN MIGUEL|CALATNGAN",
            "SAN MIGUEL|CARROMATA",
            "SAN MIGUEL|CASTILLO",
            "SAN MIGUEL|LIBAS GUA",
            "SAN MIGUEL|LIBAS SUD",
            "SAN MIGUEL|MAGROYONG",
            "SAN MIGUEL|MAHAYAG (MAITUM)",
            "SAN MIGUEL|PATONG",
            "SAN MIGUEL|POBLACION",
            "SAN MIGUEL|SAGBAYAN",
            "SAN MIGUEL|SAN ROQUE",
            "SAN MIGUEL|SIAGAO",
            "SAN MIGUEL|TINA",
            "SAN MIGUEL|UMALAG",
            "TAGBINA|BATUNAN",
            "TAGBINA|CARPENITO",
            "TAGBINA|DOÑA CARMEN",
            "TAGBINA|HINAGDANAN",
            "TAGBINA|KAHAYAGAN",
            "TAGBINA|LAGO",
            "TAGBINA|MAGLAMBING",
            "TAGBINA|MAGLATAB",
            "TAGBINA|MAGSAYSAY",
            "TAGBINA|MALIXI",
            "TAGBINA|MANAMBIA",
            "TAGBINA|OSMEÑA",
            "TAGBINA|POBLACION",
            "TAGBINA|QUEZON",
            "TAGBINA|SAN VICENTE",
            "TAGBINA|SANTA CRUZ",
            "TAGBINA|SANTA FE",
            "TAGBINA|SANTA JUANA",
            "TAGBINA|SANTA MARIA",
            "TAGBINA|SAYON",
            "TAGBINA|SORIANO",
            "TAGBINA|TAGONGON",
            "TAGBINA|TRINIDAD",
            "TAGBINA|UGOBAN",
            "TAGBINA|VILLAVERDE",
            "TAGO|ALBA",
            "TAGO|ANAHAO BAG-O",
            "TAGO|ANAHAO DAAN",
            "TAGO|BADONG",
            "TAGO|BAJAO",
            "TAGO|BANGSUD",
            "TAGO|CABANGAHAN",
            "TAGO|CAGDAPAO",
            "TAGO|CAMAGONG",
            "TAGO|CARAS-AN",
            "TAGO|CAYALE",
            "TAGO|DAYO-AN",
            "TAGO|GAMUT",
            "TAGO|JUBANG",
            "TAGO|KINABIGTASAN",
            "TAGO|LAYOG",
            "TAGO|LINDOY",
            "TAGO|MERCEDES",
            "TAGO|PURISIMA (POB.)",
            "TAGO|SUMO-SUMO",
            "TAGO|UMBAY",
            "TAGO|UNABAN",
            "TAGO|UNIDOS",
            "TAGO|VICTORIA",
            "TANDAG CITY|AWASIAN",
            "TANDAG CITY|BAGONG LUNGSOD (POB.)",
            "TANDAG CITY|BIOTO",
            "TANDAG CITY|BONGTOD POB. (EAST WEST)",
            "TANDAG CITY|BUENAVISTA",
            "TANDAG CITY|DAGOCDOC (POB.)",
            "TANDAG CITY|MABUA",
            "TANDAG CITY|MABUHAY",
            "TANDAG CITY|MAITUM",
            "TANDAG CITY|MATICDUM",
            "TANDAG CITY|PANDANON",
            "TANDAG CITY|PANGI",
            "TANDAG CITY|QUEZON",
            "TANDAG CITY|ROSARIO",
            "TANDAG CITY|SALVACION",
            "TANDAG CITY|SAN AGUSTIN NORTE",
            "TANDAG CITY|SAN AGUSTIN SUR",
            "TANDAG CITY|SAN ANTONIO",
            "TANDAG CITY|SAN ISIDRO",
            "TANDAG CITY|SAN JOSE",
            "TANDAG CITY|TELAJE",
    };
}
